//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicsNav.Plugin.SOAP.Vendors {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/vendors", ConfigurationName="SOAP.Vendors.Vendors_Port")]
    public interface Vendors_Port {
        
        // CODEGEN: Generating message contract since the wrapper name (Read_Result) of message Read_Result does not match the default value (Read)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/vendors:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DynamicsNav.Plugin.SOAP.Vendors.Read_Result Read(DynamicsNav.Plugin.SOAP.Vendors.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/vendors:Read", ReplyAction="*")]
        System.Threading.Tasks.Task<DynamicsNav.Plugin.SOAP.Vendors.Read_Result> ReadAsync(DynamicsNav.Plugin.SOAP.Vendors.Read request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadByRecId_Result) of message ReadByRecId_Result does not match the default value (ReadByRecId)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/vendors:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DynamicsNav.Plugin.SOAP.Vendors.ReadByRecId_Result ReadByRecId(DynamicsNav.Plugin.SOAP.Vendors.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/vendors:ReadByRecId", ReplyAction="*")]
        System.Threading.Tasks.Task<DynamicsNav.Plugin.SOAP.Vendors.ReadByRecId_Result> ReadByRecIdAsync(DynamicsNav.Plugin.SOAP.Vendors.ReadByRecId request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadMultiple_Result) of message ReadMultiple_Result does not match the default value (ReadMultiple)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/vendors:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DynamicsNav.Plugin.SOAP.Vendors.ReadMultiple_Result ReadMultiple(DynamicsNav.Plugin.SOAP.Vendors.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/vendors:ReadMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<DynamicsNav.Plugin.SOAP.Vendors.ReadMultiple_Result> ReadMultipleAsync(DynamicsNav.Plugin.SOAP.Vendors.ReadMultiple request);
        
        // CODEGEN: Generating message contract since the wrapper name (IsUpdated_Result) of message IsUpdated_Result does not match the default value (IsUpdated)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/vendors:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DynamicsNav.Plugin.SOAP.Vendors.IsUpdated_Result IsUpdated(DynamicsNav.Plugin.SOAP.Vendors.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/vendors:IsUpdated", ReplyAction="*")]
        System.Threading.Tasks.Task<DynamicsNav.Plugin.SOAP.Vendors.IsUpdated_Result> IsUpdatedAsync(DynamicsNav.Plugin.SOAP.Vendors.IsUpdated request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetRecIdFromKey_Result) of message GetRecIdFromKey_Result does not match the default value (GetRecIdFromKey)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/vendors:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DynamicsNav.Plugin.SOAP.Vendors.GetRecIdFromKey_Result GetRecIdFromKey(DynamicsNav.Plugin.SOAP.Vendors.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/vendors:GetRecIdFromKey", ReplyAction="*")]
        System.Threading.Tasks.Task<DynamicsNav.Plugin.SOAP.Vendors.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(DynamicsNav.Plugin.SOAP.Vendors.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/vendors:Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DynamicsNav.Plugin.SOAP.Vendors.Create_Result Create(DynamicsNav.Plugin.SOAP.Vendors.Create request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/vendors:Create", ReplyAction="*")]
        System.Threading.Tasks.Task<DynamicsNav.Plugin.SOAP.Vendors.Create_Result> CreateAsync(DynamicsNav.Plugin.SOAP.Vendors.Create request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/vendors:CreateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DynamicsNav.Plugin.SOAP.Vendors.CreateMultiple_Result CreateMultiple(DynamicsNav.Plugin.SOAP.Vendors.CreateMultiple request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/vendors:CreateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<DynamicsNav.Plugin.SOAP.Vendors.CreateMultiple_Result> CreateMultipleAsync(DynamicsNav.Plugin.SOAP.Vendors.CreateMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/vendors:Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DynamicsNav.Plugin.SOAP.Vendors.Update_Result Update(DynamicsNav.Plugin.SOAP.Vendors.Update request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/vendors:Update", ReplyAction="*")]
        System.Threading.Tasks.Task<DynamicsNav.Plugin.SOAP.Vendors.Update_Result> UpdateAsync(DynamicsNav.Plugin.SOAP.Vendors.Update request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/vendors:UpdateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DynamicsNav.Plugin.SOAP.Vendors.UpdateMultiple_Result UpdateMultiple(DynamicsNav.Plugin.SOAP.Vendors.UpdateMultiple request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/vendors:UpdateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<DynamicsNav.Plugin.SOAP.Vendors.UpdateMultiple_Result> UpdateMultipleAsync(DynamicsNav.Plugin.SOAP.Vendors.UpdateMultiple request);
        
        // CODEGEN: Generating message contract since the wrapper name (Delete_Result) of message Delete_Result does not match the default value (Delete)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/vendors:Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DynamicsNav.Plugin.SOAP.Vendors.Delete_Result Delete(DynamicsNav.Plugin.SOAP.Vendors.Delete request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/vendors:Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<DynamicsNav.Plugin.SOAP.Vendors.Delete_Result> DeleteAsync(DynamicsNav.Plugin.SOAP.Vendors.Delete request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/vendors")]
    public partial class Vendors : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string noField;
        
        private string nameField;
        
        private Blocked blockedField;
        
        private bool blockedFieldSpecified;
        
        private System.DateTime last_Date_ModifiedField;
        
        private bool last_Date_ModifiedFieldSpecified;
        
        private decimal balance_LCYField;
        
        private bool balance_LCYFieldSpecified;
        
        private decimal balance_Due_LCYField;
        
        private bool balance_Due_LCYFieldSpecified;
        
        private string document_Sending_ProfileField;
        
        private string search_NameField;
        
        private string purchaser_CodeField;
        
        private string responsibility_CenterField;
        
        private string addressField;
        
        private string address_2Field;
        
        private string post_CodeField;
        
        private string cityField;
        
        private string country_Region_CodeField;
        
        private string showMapField;
        
        private string primary_Contact_NoField;
        
        private string contactField;
        
        private string phone_NoField;
        
        private string e_MailField;
        
        private string fax_NoField;
        
        private string home_PageField;
        
        private string our_Account_NoField;
        
        private string vAT_Registration_NoField;
        
        private string gLNField;
        
        private string pay_to_Vendor_NoField;
        
        private string invoice_Disc_CodeField;
        
        private bool prices_Including_VATField;
        
        private bool prices_Including_VATFieldSpecified;
        
        private string registration_NoField;
        
        private string gen_Bus_Posting_GroupField;
        
        private string vAT_Bus_Posting_GroupField;
        
        private string vendor_Posting_GroupField;
        
        private string currency_CodeField;
        
        private string language_CodeField;
        
        private Application_Method application_MethodField;
        
        private bool application_MethodFieldSpecified;
        
        private string payment_Terms_CodeField;
        
        private string payment_Method_CodeField;
        
        private int priorityField;
        
        private bool priorityFieldSpecified;
        
        private bool block_Payment_ToleranceField;
        
        private bool block_Payment_ToleranceFieldSpecified;
        
        private string preferred_Bank_Account_CodeField;
        
        private Partner_Type partner_TypeField;
        
        private bool partner_TypeFieldSpecified;
        
        private string cash_Flow_Payment_Terms_CodeField;
        
        private string creditor_NoField;
        
        private string location_CodeField;
        
        private string shipment_Method_CodeField;
        
        private string lead_Time_CalculationField;
        
        private string base_Calendar_CodeField;
        
        private string customized_CalendarField;
        
        private string delivery_Reminder_TermsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
                this.RaisePropertyChanged("No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Blocked Blocked {
            get {
                return this.blockedField;
            }
            set {
                this.blockedField = value;
                this.RaisePropertyChanged("Blocked");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BlockedSpecified {
            get {
                return this.blockedFieldSpecified;
            }
            set {
                this.blockedFieldSpecified = value;
                this.RaisePropertyChanged("BlockedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=4)]
        public System.DateTime Last_Date_Modified {
            get {
                return this.last_Date_ModifiedField;
            }
            set {
                this.last_Date_ModifiedField = value;
                this.RaisePropertyChanged("Last_Date_Modified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Last_Date_ModifiedSpecified {
            get {
                return this.last_Date_ModifiedFieldSpecified;
            }
            set {
                this.last_Date_ModifiedFieldSpecified = value;
                this.RaisePropertyChanged("Last_Date_ModifiedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal Balance_LCY {
            get {
                return this.balance_LCYField;
            }
            set {
                this.balance_LCYField = value;
                this.RaisePropertyChanged("Balance_LCY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Balance_LCYSpecified {
            get {
                return this.balance_LCYFieldSpecified;
            }
            set {
                this.balance_LCYFieldSpecified = value;
                this.RaisePropertyChanged("Balance_LCYSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public decimal Balance_Due_LCY {
            get {
                return this.balance_Due_LCYField;
            }
            set {
                this.balance_Due_LCYField = value;
                this.RaisePropertyChanged("Balance_Due_LCY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Balance_Due_LCYSpecified {
            get {
                return this.balance_Due_LCYFieldSpecified;
            }
            set {
                this.balance_Due_LCYFieldSpecified = value;
                this.RaisePropertyChanged("Balance_Due_LCYSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Document_Sending_Profile {
            get {
                return this.document_Sending_ProfileField;
            }
            set {
                this.document_Sending_ProfileField = value;
                this.RaisePropertyChanged("Document_Sending_Profile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Search_Name {
            get {
                return this.search_NameField;
            }
            set {
                this.search_NameField = value;
                this.RaisePropertyChanged("Search_Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Purchaser_Code {
            get {
                return this.purchaser_CodeField;
            }
            set {
                this.purchaser_CodeField = value;
                this.RaisePropertyChanged("Purchaser_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Responsibility_Center {
            get {
                return this.responsibility_CenterField;
            }
            set {
                this.responsibility_CenterField = value;
                this.RaisePropertyChanged("Responsibility_Center");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Address_2 {
            get {
                return this.address_2Field;
            }
            set {
                this.address_2Field = value;
                this.RaisePropertyChanged("Address_2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Post_Code {
            get {
                return this.post_CodeField;
            }
            set {
                this.post_CodeField = value;
                this.RaisePropertyChanged("Post_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Country_Region_Code {
            get {
                return this.country_Region_CodeField;
            }
            set {
                this.country_Region_CodeField = value;
                this.RaisePropertyChanged("Country_Region_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string ShowMap {
            get {
                return this.showMapField;
            }
            set {
                this.showMapField = value;
                this.RaisePropertyChanged("ShowMap");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string Primary_Contact_No {
            get {
                return this.primary_Contact_NoField;
            }
            set {
                this.primary_Contact_NoField = value;
                this.RaisePropertyChanged("Primary_Contact_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
                this.RaisePropertyChanged("Contact");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Phone_No {
            get {
                return this.phone_NoField;
            }
            set {
                this.phone_NoField = value;
                this.RaisePropertyChanged("Phone_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string E_Mail {
            get {
                return this.e_MailField;
            }
            set {
                this.e_MailField = value;
                this.RaisePropertyChanged("E_Mail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string Fax_No {
            get {
                return this.fax_NoField;
            }
            set {
                this.fax_NoField = value;
                this.RaisePropertyChanged("Fax_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string Home_Page {
            get {
                return this.home_PageField;
            }
            set {
                this.home_PageField = value;
                this.RaisePropertyChanged("Home_Page");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string Our_Account_No {
            get {
                return this.our_Account_NoField;
            }
            set {
                this.our_Account_NoField = value;
                this.RaisePropertyChanged("Our_Account_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string VAT_Registration_No {
            get {
                return this.vAT_Registration_NoField;
            }
            set {
                this.vAT_Registration_NoField = value;
                this.RaisePropertyChanged("VAT_Registration_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string GLN {
            get {
                return this.gLNField;
            }
            set {
                this.gLNField = value;
                this.RaisePropertyChanged("GLN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string Pay_to_Vendor_No {
            get {
                return this.pay_to_Vendor_NoField;
            }
            set {
                this.pay_to_Vendor_NoField = value;
                this.RaisePropertyChanged("Pay_to_Vendor_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string Invoice_Disc_Code {
            get {
                return this.invoice_Disc_CodeField;
            }
            set {
                this.invoice_Disc_CodeField = value;
                this.RaisePropertyChanged("Invoice_Disc_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public bool Prices_Including_VAT {
            get {
                return this.prices_Including_VATField;
            }
            set {
                this.prices_Including_VATField = value;
                this.RaisePropertyChanged("Prices_Including_VAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Prices_Including_VATSpecified {
            get {
                return this.prices_Including_VATFieldSpecified;
            }
            set {
                this.prices_Including_VATFieldSpecified = value;
                this.RaisePropertyChanged("Prices_Including_VATSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string Registration_No {
            get {
                return this.registration_NoField;
            }
            set {
                this.registration_NoField = value;
                this.RaisePropertyChanged("Registration_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string Gen_Bus_Posting_Group {
            get {
                return this.gen_Bus_Posting_GroupField;
            }
            set {
                this.gen_Bus_Posting_GroupField = value;
                this.RaisePropertyChanged("Gen_Bus_Posting_Group");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string VAT_Bus_Posting_Group {
            get {
                return this.vAT_Bus_Posting_GroupField;
            }
            set {
                this.vAT_Bus_Posting_GroupField = value;
                this.RaisePropertyChanged("VAT_Bus_Posting_Group");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string Vendor_Posting_Group {
            get {
                return this.vendor_Posting_GroupField;
            }
            set {
                this.vendor_Posting_GroupField = value;
                this.RaisePropertyChanged("Vendor_Posting_Group");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string Currency_Code {
            get {
                return this.currency_CodeField;
            }
            set {
                this.currency_CodeField = value;
                this.RaisePropertyChanged("Currency_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string Language_Code {
            get {
                return this.language_CodeField;
            }
            set {
                this.language_CodeField = value;
                this.RaisePropertyChanged("Language_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public Application_Method Application_Method {
            get {
                return this.application_MethodField;
            }
            set {
                this.application_MethodField = value;
                this.RaisePropertyChanged("Application_Method");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Application_MethodSpecified {
            get {
                return this.application_MethodFieldSpecified;
            }
            set {
                this.application_MethodFieldSpecified = value;
                this.RaisePropertyChanged("Application_MethodSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public string Payment_Terms_Code {
            get {
                return this.payment_Terms_CodeField;
            }
            set {
                this.payment_Terms_CodeField = value;
                this.RaisePropertyChanged("Payment_Terms_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public string Payment_Method_Code {
            get {
                return this.payment_Method_CodeField;
            }
            set {
                this.payment_Method_CodeField = value;
                this.RaisePropertyChanged("Payment_Method_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public int Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
                this.RaisePropertyChanged("Priority");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrioritySpecified {
            get {
                return this.priorityFieldSpecified;
            }
            set {
                this.priorityFieldSpecified = value;
                this.RaisePropertyChanged("PrioritySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public bool Block_Payment_Tolerance {
            get {
                return this.block_Payment_ToleranceField;
            }
            set {
                this.block_Payment_ToleranceField = value;
                this.RaisePropertyChanged("Block_Payment_Tolerance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Block_Payment_ToleranceSpecified {
            get {
                return this.block_Payment_ToleranceFieldSpecified;
            }
            set {
                this.block_Payment_ToleranceFieldSpecified = value;
                this.RaisePropertyChanged("Block_Payment_ToleranceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public string Preferred_Bank_Account_Code {
            get {
                return this.preferred_Bank_Account_CodeField;
            }
            set {
                this.preferred_Bank_Account_CodeField = value;
                this.RaisePropertyChanged("Preferred_Bank_Account_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public Partner_Type Partner_Type {
            get {
                return this.partner_TypeField;
            }
            set {
                this.partner_TypeField = value;
                this.RaisePropertyChanged("Partner_Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Partner_TypeSpecified {
            get {
                return this.partner_TypeFieldSpecified;
            }
            set {
                this.partner_TypeFieldSpecified = value;
                this.RaisePropertyChanged("Partner_TypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public string Cash_Flow_Payment_Terms_Code {
            get {
                return this.cash_Flow_Payment_Terms_CodeField;
            }
            set {
                this.cash_Flow_Payment_Terms_CodeField = value;
                this.RaisePropertyChanged("Cash_Flow_Payment_Terms_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=43)]
        public string Creditor_No {
            get {
                return this.creditor_NoField;
            }
            set {
                this.creditor_NoField = value;
                this.RaisePropertyChanged("Creditor_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=44)]
        public string Location_Code {
            get {
                return this.location_CodeField;
            }
            set {
                this.location_CodeField = value;
                this.RaisePropertyChanged("Location_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=45)]
        public string Shipment_Method_Code {
            get {
                return this.shipment_Method_CodeField;
            }
            set {
                this.shipment_Method_CodeField = value;
                this.RaisePropertyChanged("Shipment_Method_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=46)]
        public string Lead_Time_Calculation {
            get {
                return this.lead_Time_CalculationField;
            }
            set {
                this.lead_Time_CalculationField = value;
                this.RaisePropertyChanged("Lead_Time_Calculation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=47)]
        public string Base_Calendar_Code {
            get {
                return this.base_Calendar_CodeField;
            }
            set {
                this.base_Calendar_CodeField = value;
                this.RaisePropertyChanged("Base_Calendar_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=48)]
        public string Customized_Calendar {
            get {
                return this.customized_CalendarField;
            }
            set {
                this.customized_CalendarField = value;
                this.RaisePropertyChanged("Customized_Calendar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=49)]
        public string Delivery_Reminder_Terms {
            get {
                return this.delivery_Reminder_TermsField;
            }
            set {
                this.delivery_Reminder_TermsField = value;
                this.RaisePropertyChanged("Delivery_Reminder_Terms");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/vendors")]
    public enum Blocked {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Payment,
        
        /// <remarks/>
        All,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/vendors")]
    public enum Application_Method {
        
        /// <remarks/>
        Manual,
        
        /// <remarks/>
        Apply_to_Oldest,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/vendors")]
    public enum Partner_Type {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Company,
        
        /// <remarks/>
        Person,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/vendors")]
    public partial class Vendors_Filter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Vendors_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Vendors_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
                this.RaisePropertyChanged("Criteria");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/vendors")]
    public enum Vendors_Fields {
        
        /// <remarks/>
        No,
        
        /// <remarks/>
        Name,
        
        /// <remarks/>
        Blocked,
        
        /// <remarks/>
        Last_Date_Modified,
        
        /// <remarks/>
        Balance_LCY,
        
        /// <remarks/>
        Balance_Due_LCY,
        
        /// <remarks/>
        Document_Sending_Profile,
        
        /// <remarks/>
        Search_Name,
        
        /// <remarks/>
        Purchaser_Code,
        
        /// <remarks/>
        Responsibility_Center,
        
        /// <remarks/>
        Address,
        
        /// <remarks/>
        Address_2,
        
        /// <remarks/>
        Post_Code,
        
        /// <remarks/>
        City,
        
        /// <remarks/>
        Country_Region_Code,
        
        /// <remarks/>
        ShowMap,
        
        /// <remarks/>
        Primary_Contact_No,
        
        /// <remarks/>
        Contact,
        
        /// <remarks/>
        Phone_No,
        
        /// <remarks/>
        E_Mail,
        
        /// <remarks/>
        Fax_No,
        
        /// <remarks/>
        Home_Page,
        
        /// <remarks/>
        Our_Account_No,
        
        /// <remarks/>
        VAT_Registration_No,
        
        /// <remarks/>
        GLN,
        
        /// <remarks/>
        Pay_to_Vendor_No,
        
        /// <remarks/>
        Invoice_Disc_Code,
        
        /// <remarks/>
        Prices_Including_VAT,
        
        /// <remarks/>
        Registration_No,
        
        /// <remarks/>
        Gen_Bus_Posting_Group,
        
        /// <remarks/>
        VAT_Bus_Posting_Group,
        
        /// <remarks/>
        Vendor_Posting_Group,
        
        /// <remarks/>
        Currency_Code,
        
        /// <remarks/>
        Language_Code,
        
        /// <remarks/>
        Application_Method,
        
        /// <remarks/>
        Payment_Terms_Code,
        
        /// <remarks/>
        Payment_Method_Code,
        
        /// <remarks/>
        Priority,
        
        /// <remarks/>
        Block_Payment_Tolerance,
        
        /// <remarks/>
        Preferred_Bank_Account_Code,
        
        /// <remarks/>
        Partner_Type,
        
        /// <remarks/>
        Cash_Flow_Payment_Terms_Code,
        
        /// <remarks/>
        Creditor_No,
        
        /// <remarks/>
        Location_Code,
        
        /// <remarks/>
        Shipment_Method_Code,
        
        /// <remarks/>
        Lead_Time_Calculation,
        
        /// <remarks/>
        Base_Calendar_Code,
        
        /// <remarks/>
        Customized_Calendar,
        
        /// <remarks/>
        Delivery_Reminder_Terms,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/vendors", IsWrapped=true)]
    public partial class Read {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/vendors", Order=0)]
        public string No;
        
        public Read() {
        }
        
        public Read(string No) {
            this.No = No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/vendors", IsWrapped=true)]
    public partial class Read_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/vendors", Order=0)]
        public DynamicsNav.Plugin.SOAP.Vendors.Vendors Vendors;
        
        public Read_Result() {
        }
        
        public Read_Result(DynamicsNav.Plugin.SOAP.Vendors.Vendors Vendors) {
            this.Vendors = Vendors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/vendors", IsWrapped=true)]
    public partial class ReadByRecId {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/vendors", Order=0)]
        public string recId;
        
        public ReadByRecId() {
        }
        
        public ReadByRecId(string recId) {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/vendors", IsWrapped=true)]
    public partial class ReadByRecId_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/vendors", Order=0)]
        public DynamicsNav.Plugin.SOAP.Vendors.Vendors Vendors;
        
        public ReadByRecId_Result() {
        }
        
        public ReadByRecId_Result(DynamicsNav.Plugin.SOAP.Vendors.Vendors Vendors) {
            this.Vendors = Vendors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/vendors", IsWrapped=true)]
    public partial class ReadMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/vendors", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public DynamicsNav.Plugin.SOAP.Vendors.Vendors_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/vendors", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/vendors", Order=2)]
        public int setSize;
        
        public ReadMultiple() {
        }
        
        public ReadMultiple(DynamicsNav.Plugin.SOAP.Vendors.Vendors_Filter[] filter, string bookmarkKey, int setSize) {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/vendors", IsWrapped=true)]
    public partial class ReadMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/vendors", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public DynamicsNav.Plugin.SOAP.Vendors.Vendors[] ReadMultiple_Result1;
        
        public ReadMultiple_Result() {
        }
        
        public ReadMultiple_Result(DynamicsNav.Plugin.SOAP.Vendors.Vendors[] ReadMultiple_Result1) {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/vendors", IsWrapped=true)]
    public partial class IsUpdated {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/vendors", Order=0)]
        public string Key;
        
        public IsUpdated() {
        }
        
        public IsUpdated(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/vendors", IsWrapped=true)]
    public partial class IsUpdated_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/vendors", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result() {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1) {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/vendors", IsWrapped=true)]
    public partial class GetRecIdFromKey {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/vendors", Order=0)]
        public string Key;
        
        public GetRecIdFromKey() {
        }
        
        public GetRecIdFromKey(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/vendors", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/vendors", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result() {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1) {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create", WrapperNamespace="urn:microsoft-dynamics-schemas/page/vendors", IsWrapped=true)]
    public partial class Create {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/vendors", Order=0)]
        public DynamicsNav.Plugin.SOAP.Vendors.Vendors Vendors;
        
        public Create() {
        }
        
        public Create(DynamicsNav.Plugin.SOAP.Vendors.Vendors Vendors) {
            this.Vendors = Vendors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/vendors", IsWrapped=true)]
    public partial class Create_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/vendors", Order=0)]
        public DynamicsNav.Plugin.SOAP.Vendors.Vendors Vendors;
        
        public Create_Result() {
        }
        
        public Create_Result(DynamicsNav.Plugin.SOAP.Vendors.Vendors Vendors) {
            this.Vendors = Vendors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/vendors", IsWrapped=true)]
    public partial class CreateMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/vendors", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public DynamicsNav.Plugin.SOAP.Vendors.Vendors[] Vendors_List;
        
        public CreateMultiple() {
        }
        
        public CreateMultiple(DynamicsNav.Plugin.SOAP.Vendors.Vendors[] Vendors_List) {
            this.Vendors_List = Vendors_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/vendors", IsWrapped=true)]
    public partial class CreateMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/vendors", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public DynamicsNav.Plugin.SOAP.Vendors.Vendors[] Vendors_List;
        
        public CreateMultiple_Result() {
        }
        
        public CreateMultiple_Result(DynamicsNav.Plugin.SOAP.Vendors.Vendors[] Vendors_List) {
            this.Vendors_List = Vendors_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="urn:microsoft-dynamics-schemas/page/vendors", IsWrapped=true)]
    public partial class Update {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/vendors", Order=0)]
        public DynamicsNav.Plugin.SOAP.Vendors.Vendors Vendors;
        
        public Update() {
        }
        
        public Update(DynamicsNav.Plugin.SOAP.Vendors.Vendors Vendors) {
            this.Vendors = Vendors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/vendors", IsWrapped=true)]
    public partial class Update_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/vendors", Order=0)]
        public DynamicsNav.Plugin.SOAP.Vendors.Vendors Vendors;
        
        public Update_Result() {
        }
        
        public Update_Result(DynamicsNav.Plugin.SOAP.Vendors.Vendors Vendors) {
            this.Vendors = Vendors;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/vendors", IsWrapped=true)]
    public partial class UpdateMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/vendors", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public DynamicsNav.Plugin.SOAP.Vendors.Vendors[] Vendors_List;
        
        public UpdateMultiple() {
        }
        
        public UpdateMultiple(DynamicsNav.Plugin.SOAP.Vendors.Vendors[] Vendors_List) {
            this.Vendors_List = Vendors_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/vendors", IsWrapped=true)]
    public partial class UpdateMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/vendors", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public DynamicsNav.Plugin.SOAP.Vendors.Vendors[] Vendors_List;
        
        public UpdateMultiple_Result() {
        }
        
        public UpdateMultiple_Result(DynamicsNav.Plugin.SOAP.Vendors.Vendors[] Vendors_List) {
            this.Vendors_List = Vendors_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete", WrapperNamespace="urn:microsoft-dynamics-schemas/page/vendors", IsWrapped=true)]
    public partial class Delete {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/vendors", Order=0)]
        public string Key;
        
        public Delete() {
        }
        
        public Delete(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/vendors", IsWrapped=true)]
    public partial class Delete_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_Result", Namespace="urn:microsoft-dynamics-schemas/page/vendors", Order=0)]
        public bool Delete_Result1;
        
        public Delete_Result() {
        }
        
        public Delete_Result(bool Delete_Result1) {
            this.Delete_Result1 = Delete_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Vendors_PortChannel : DynamicsNav.Plugin.SOAP.Vendors.Vendors_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Vendors_PortClient : System.ServiceModel.ClientBase<DynamicsNav.Plugin.SOAP.Vendors.Vendors_Port>, DynamicsNav.Plugin.SOAP.Vendors.Vendors_Port {
        
        public Vendors_PortClient() {
        }
        
        public Vendors_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Vendors_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Vendors_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Vendors_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DynamicsNav.Plugin.SOAP.Vendors.Read_Result DynamicsNav.Plugin.SOAP.Vendors.Vendors_Port.Read(DynamicsNav.Plugin.SOAP.Vendors.Read request) {
            return base.Channel.Read(request);
        }
        
        public DynamicsNav.Plugin.SOAP.Vendors.Vendors Read(string No) {
            DynamicsNav.Plugin.SOAP.Vendors.Read inValue = new DynamicsNav.Plugin.SOAP.Vendors.Read();
            inValue.No = No;
            DynamicsNav.Plugin.SOAP.Vendors.Read_Result retVal = ((DynamicsNav.Plugin.SOAP.Vendors.Vendors_Port)(this)).Read(inValue);
            return retVal.Vendors;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DynamicsNav.Plugin.SOAP.Vendors.Read_Result> DynamicsNav.Plugin.SOAP.Vendors.Vendors_Port.ReadAsync(DynamicsNav.Plugin.SOAP.Vendors.Read request) {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<DynamicsNav.Plugin.SOAP.Vendors.Read_Result> ReadAsync(string No) {
            DynamicsNav.Plugin.SOAP.Vendors.Read inValue = new DynamicsNav.Plugin.SOAP.Vendors.Read();
            inValue.No = No;
            return ((DynamicsNav.Plugin.SOAP.Vendors.Vendors_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DynamicsNav.Plugin.SOAP.Vendors.ReadByRecId_Result DynamicsNav.Plugin.SOAP.Vendors.Vendors_Port.ReadByRecId(DynamicsNav.Plugin.SOAP.Vendors.ReadByRecId request) {
            return base.Channel.ReadByRecId(request);
        }
        
        public DynamicsNav.Plugin.SOAP.Vendors.Vendors ReadByRecId(string recId) {
            DynamicsNav.Plugin.SOAP.Vendors.ReadByRecId inValue = new DynamicsNav.Plugin.SOAP.Vendors.ReadByRecId();
            inValue.recId = recId;
            DynamicsNav.Plugin.SOAP.Vendors.ReadByRecId_Result retVal = ((DynamicsNav.Plugin.SOAP.Vendors.Vendors_Port)(this)).ReadByRecId(inValue);
            return retVal.Vendors;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DynamicsNav.Plugin.SOAP.Vendors.ReadByRecId_Result> DynamicsNav.Plugin.SOAP.Vendors.Vendors_Port.ReadByRecIdAsync(DynamicsNav.Plugin.SOAP.Vendors.ReadByRecId request) {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<DynamicsNav.Plugin.SOAP.Vendors.ReadByRecId_Result> ReadByRecIdAsync(string recId) {
            DynamicsNav.Plugin.SOAP.Vendors.ReadByRecId inValue = new DynamicsNav.Plugin.SOAP.Vendors.ReadByRecId();
            inValue.recId = recId;
            return ((DynamicsNav.Plugin.SOAP.Vendors.Vendors_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DynamicsNav.Plugin.SOAP.Vendors.ReadMultiple_Result DynamicsNav.Plugin.SOAP.Vendors.Vendors_Port.ReadMultiple(DynamicsNav.Plugin.SOAP.Vendors.ReadMultiple request) {
            return base.Channel.ReadMultiple(request);
        }
        
        public DynamicsNav.Plugin.SOAP.Vendors.Vendors[] ReadMultiple(DynamicsNav.Plugin.SOAP.Vendors.Vendors_Filter[] filter, string bookmarkKey, int setSize) {
            DynamicsNav.Plugin.SOAP.Vendors.ReadMultiple inValue = new DynamicsNav.Plugin.SOAP.Vendors.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            DynamicsNav.Plugin.SOAP.Vendors.ReadMultiple_Result retVal = ((DynamicsNav.Plugin.SOAP.Vendors.Vendors_Port)(this)).ReadMultiple(inValue);
            return retVal.ReadMultiple_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DynamicsNav.Plugin.SOAP.Vendors.ReadMultiple_Result> DynamicsNav.Plugin.SOAP.Vendors.Vendors_Port.ReadMultipleAsync(DynamicsNav.Plugin.SOAP.Vendors.ReadMultiple request) {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<DynamicsNav.Plugin.SOAP.Vendors.ReadMultiple_Result> ReadMultipleAsync(DynamicsNav.Plugin.SOAP.Vendors.Vendors_Filter[] filter, string bookmarkKey, int setSize) {
            DynamicsNav.Plugin.SOAP.Vendors.ReadMultiple inValue = new DynamicsNav.Plugin.SOAP.Vendors.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((DynamicsNav.Plugin.SOAP.Vendors.Vendors_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DynamicsNav.Plugin.SOAP.Vendors.IsUpdated_Result DynamicsNav.Plugin.SOAP.Vendors.Vendors_Port.IsUpdated(DynamicsNav.Plugin.SOAP.Vendors.IsUpdated request) {
            return base.Channel.IsUpdated(request);
        }
        
        public bool IsUpdated(string Key) {
            DynamicsNav.Plugin.SOAP.Vendors.IsUpdated inValue = new DynamicsNav.Plugin.SOAP.Vendors.IsUpdated();
            inValue.Key = Key;
            DynamicsNav.Plugin.SOAP.Vendors.IsUpdated_Result retVal = ((DynamicsNav.Plugin.SOAP.Vendors.Vendors_Port)(this)).IsUpdated(inValue);
            return retVal.IsUpdated_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DynamicsNav.Plugin.SOAP.Vendors.IsUpdated_Result> DynamicsNav.Plugin.SOAP.Vendors.Vendors_Port.IsUpdatedAsync(DynamicsNav.Plugin.SOAP.Vendors.IsUpdated request) {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<DynamicsNav.Plugin.SOAP.Vendors.IsUpdated_Result> IsUpdatedAsync(string Key) {
            DynamicsNav.Plugin.SOAP.Vendors.IsUpdated inValue = new DynamicsNav.Plugin.SOAP.Vendors.IsUpdated();
            inValue.Key = Key;
            return ((DynamicsNav.Plugin.SOAP.Vendors.Vendors_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DynamicsNav.Plugin.SOAP.Vendors.GetRecIdFromKey_Result DynamicsNav.Plugin.SOAP.Vendors.Vendors_Port.GetRecIdFromKey(DynamicsNav.Plugin.SOAP.Vendors.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKey(request);
        }
        
        public string GetRecIdFromKey(string Key) {
            DynamicsNav.Plugin.SOAP.Vendors.GetRecIdFromKey inValue = new DynamicsNav.Plugin.SOAP.Vendors.GetRecIdFromKey();
            inValue.Key = Key;
            DynamicsNav.Plugin.SOAP.Vendors.GetRecIdFromKey_Result retVal = ((DynamicsNav.Plugin.SOAP.Vendors.Vendors_Port)(this)).GetRecIdFromKey(inValue);
            return retVal.GetRecIdFromKey_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DynamicsNav.Plugin.SOAP.Vendors.GetRecIdFromKey_Result> DynamicsNav.Plugin.SOAP.Vendors.Vendors_Port.GetRecIdFromKeyAsync(DynamicsNav.Plugin.SOAP.Vendors.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<DynamicsNav.Plugin.SOAP.Vendors.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key) {
            DynamicsNav.Plugin.SOAP.Vendors.GetRecIdFromKey inValue = new DynamicsNav.Plugin.SOAP.Vendors.GetRecIdFromKey();
            inValue.Key = Key;
            return ((DynamicsNav.Plugin.SOAP.Vendors.Vendors_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DynamicsNav.Plugin.SOAP.Vendors.Create_Result DynamicsNav.Plugin.SOAP.Vendors.Vendors_Port.Create(DynamicsNav.Plugin.SOAP.Vendors.Create request) {
            return base.Channel.Create(request);
        }
        
        public void Create(ref DynamicsNav.Plugin.SOAP.Vendors.Vendors Vendors) {
            DynamicsNav.Plugin.SOAP.Vendors.Create inValue = new DynamicsNav.Plugin.SOAP.Vendors.Create();
            inValue.Vendors = Vendors;
            DynamicsNav.Plugin.SOAP.Vendors.Create_Result retVal = ((DynamicsNav.Plugin.SOAP.Vendors.Vendors_Port)(this)).Create(inValue);
            Vendors = retVal.Vendors;
        }
        
        public System.Threading.Tasks.Task<DynamicsNav.Plugin.SOAP.Vendors.Create_Result> CreateAsync(DynamicsNav.Plugin.SOAP.Vendors.Create request) {
            return base.Channel.CreateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DynamicsNav.Plugin.SOAP.Vendors.CreateMultiple_Result DynamicsNav.Plugin.SOAP.Vendors.Vendors_Port.CreateMultiple(DynamicsNav.Plugin.SOAP.Vendors.CreateMultiple request) {
            return base.Channel.CreateMultiple(request);
        }
        
        public void CreateMultiple(ref DynamicsNav.Plugin.SOAP.Vendors.Vendors[] Vendors_List) {
            DynamicsNav.Plugin.SOAP.Vendors.CreateMultiple inValue = new DynamicsNav.Plugin.SOAP.Vendors.CreateMultiple();
            inValue.Vendors_List = Vendors_List;
            DynamicsNav.Plugin.SOAP.Vendors.CreateMultiple_Result retVal = ((DynamicsNav.Plugin.SOAP.Vendors.Vendors_Port)(this)).CreateMultiple(inValue);
            Vendors_List = retVal.Vendors_List;
        }
        
        public System.Threading.Tasks.Task<DynamicsNav.Plugin.SOAP.Vendors.CreateMultiple_Result> CreateMultipleAsync(DynamicsNav.Plugin.SOAP.Vendors.CreateMultiple request) {
            return base.Channel.CreateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DynamicsNav.Plugin.SOAP.Vendors.Update_Result DynamicsNav.Plugin.SOAP.Vendors.Vendors_Port.Update(DynamicsNav.Plugin.SOAP.Vendors.Update request) {
            return base.Channel.Update(request);
        }
        
        public void Update(ref DynamicsNav.Plugin.SOAP.Vendors.Vendors Vendors) {
            DynamicsNav.Plugin.SOAP.Vendors.Update inValue = new DynamicsNav.Plugin.SOAP.Vendors.Update();
            inValue.Vendors = Vendors;
            DynamicsNav.Plugin.SOAP.Vendors.Update_Result retVal = ((DynamicsNav.Plugin.SOAP.Vendors.Vendors_Port)(this)).Update(inValue);
            Vendors = retVal.Vendors;
        }
        
        public System.Threading.Tasks.Task<DynamicsNav.Plugin.SOAP.Vendors.Update_Result> UpdateAsync(DynamicsNav.Plugin.SOAP.Vendors.Update request) {
            return base.Channel.UpdateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DynamicsNav.Plugin.SOAP.Vendors.UpdateMultiple_Result DynamicsNav.Plugin.SOAP.Vendors.Vendors_Port.UpdateMultiple(DynamicsNav.Plugin.SOAP.Vendors.UpdateMultiple request) {
            return base.Channel.UpdateMultiple(request);
        }
        
        public void UpdateMultiple(ref DynamicsNav.Plugin.SOAP.Vendors.Vendors[] Vendors_List) {
            DynamicsNav.Plugin.SOAP.Vendors.UpdateMultiple inValue = new DynamicsNav.Plugin.SOAP.Vendors.UpdateMultiple();
            inValue.Vendors_List = Vendors_List;
            DynamicsNav.Plugin.SOAP.Vendors.UpdateMultiple_Result retVal = ((DynamicsNav.Plugin.SOAP.Vendors.Vendors_Port)(this)).UpdateMultiple(inValue);
            Vendors_List = retVal.Vendors_List;
        }
        
        public System.Threading.Tasks.Task<DynamicsNav.Plugin.SOAP.Vendors.UpdateMultiple_Result> UpdateMultipleAsync(DynamicsNav.Plugin.SOAP.Vendors.UpdateMultiple request) {
            return base.Channel.UpdateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DynamicsNav.Plugin.SOAP.Vendors.Delete_Result DynamicsNav.Plugin.SOAP.Vendors.Vendors_Port.Delete(DynamicsNav.Plugin.SOAP.Vendors.Delete request) {
            return base.Channel.Delete(request);
        }
        
        public bool Delete(string Key) {
            DynamicsNav.Plugin.SOAP.Vendors.Delete inValue = new DynamicsNav.Plugin.SOAP.Vendors.Delete();
            inValue.Key = Key;
            DynamicsNav.Plugin.SOAP.Vendors.Delete_Result retVal = ((DynamicsNav.Plugin.SOAP.Vendors.Vendors_Port)(this)).Delete(inValue);
            return retVal.Delete_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DynamicsNav.Plugin.SOAP.Vendors.Delete_Result> DynamicsNav.Plugin.SOAP.Vendors.Vendors_Port.DeleteAsync(DynamicsNav.Plugin.SOAP.Vendors.Delete request) {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<DynamicsNav.Plugin.SOAP.Vendors.Delete_Result> DeleteAsync(string Key) {
            DynamicsNav.Plugin.SOAP.Vendors.Delete inValue = new DynamicsNav.Plugin.SOAP.Vendors.Delete();
            inValue.Key = Key;
            return ((DynamicsNav.Plugin.SOAP.Vendors.Vendors_Port)(this)).DeleteAsync(inValue);
        }
    }
}
