//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemcategorycard", ConfigurationName="SOAP.ItemCategoryCard.ItemCategoryCard_Port")]
    public interface ItemCategoryCard_Port {
        
        // CODEGEN: Generating message contract since the wrapper name (Read_Result) of message Read_Result does not match the default value (Read)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/itemcategorycard:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.Read_Result Read(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/itemcategorycard:Read", ReplyAction="*")]
        System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.Read_Result> ReadAsync(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.Read request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadByRecId_Result) of message ReadByRecId_Result does not match the default value (ReadByRecId)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/itemcategorycard:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ReadByRecId_Result ReadByRecId(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/itemcategorycard:ReadByRecId", ReplyAction="*")]
        System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ReadByRecId_Result> ReadByRecIdAsync(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ReadByRecId request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadMultiple_Result) of message ReadMultiple_Result does not match the default value (ReadMultiple)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/itemcategorycard:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ReadMultiple_Result ReadMultiple(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/itemcategorycard:ReadMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ReadMultiple_Result> ReadMultipleAsync(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ReadMultiple request);
        
        // CODEGEN: Generating message contract since the wrapper name (IsUpdated_Result) of message IsUpdated_Result does not match the default value (IsUpdated)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/itemcategorycard:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.IsUpdated_Result IsUpdated(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/itemcategorycard:IsUpdated", ReplyAction="*")]
        System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.IsUpdated_Result> IsUpdatedAsync(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.IsUpdated request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetRecIdFromKey_Result) of message GetRecIdFromKey_Result does not match the default value (GetRecIdFromKey)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/itemcategorycard:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.GetRecIdFromKey_Result GetRecIdFromKey(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/itemcategorycard:GetRecIdFromKey", ReplyAction="*")]
        System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/itemcategorycard:Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.Create_Result Create(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.Create request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/itemcategorycard:Create", ReplyAction="*")]
        System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.Create_Result> CreateAsync(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.Create request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/itemcategorycard:CreateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.CreateMultiple_Result CreateMultiple(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.CreateMultiple request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/itemcategorycard:CreateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.CreateMultiple_Result> CreateMultipleAsync(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.CreateMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/itemcategorycard:Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.Update_Result Update(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.Update request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/itemcategorycard:Update", ReplyAction="*")]
        System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.Update_Result> UpdateAsync(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.Update request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/itemcategorycard:UpdateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.UpdateMultiple_Result UpdateMultiple(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.UpdateMultiple request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/itemcategorycard:UpdateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.UpdateMultiple_Result> UpdateMultipleAsync(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.UpdateMultiple request);
        
        // CODEGEN: Generating message contract since the wrapper name (Delete_Attributes_Result) of message Delete_Attributes_Result does not match the default value (Delete_Attributes)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/itemcategorycard:Delete_Attributes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.Delete_Attributes_Result Delete_Attributes(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.Delete_Attributes request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/itemcategorycard:Delete_Attributes", ReplyAction="*")]
        System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.Delete_Attributes_Result> Delete_AttributesAsync(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.Delete_Attributes request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemcategorycard")]
    public partial class ItemCategoryCard : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string codeField;
        
        private string descriptionField;
        
        private string parent_CategoryField;
        
        private Item_Category_Attributes[] attributesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Parent_Category {
            get {
                return this.parent_CategoryField;
            }
            set {
                this.parent_CategoryField = value;
                this.RaisePropertyChanged("Parent_Category");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Item_Category_Attributes[] Attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
                this.RaisePropertyChanged("Attributes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemcategorycard")]
    public partial class Item_Category_Attributes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string attribute_NameField;
        
        private string valueField;
        
        private string unit_of_MeasureField;
        
        private string inherited_From_Key_ValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Attribute_Name {
            get {
                return this.attribute_NameField;
            }
            set {
                this.attribute_NameField = value;
                this.RaisePropertyChanged("Attribute_Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Unit_of_Measure {
            get {
                return this.unit_of_MeasureField;
            }
            set {
                this.unit_of_MeasureField = value;
                this.RaisePropertyChanged("Unit_of_Measure");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Inherited_From_Key_Value {
            get {
                return this.inherited_From_Key_ValueField;
            }
            set {
                this.inherited_From_Key_ValueField = value;
                this.RaisePropertyChanged("Inherited_From_Key_Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemcategorycard")]
    public partial class ItemCategoryCard_Filter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ItemCategoryCard_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ItemCategoryCard_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
                this.RaisePropertyChanged("Criteria");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemcategorycard")]
    public enum ItemCategoryCard_Fields {
        
        /// <remarks/>
        Code,
        
        /// <remarks/>
        Description,
        
        /// <remarks/>
        Parent_Category,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/itemcategorycard", IsWrapped=true)]
    public partial class Read {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemcategorycard", Order=0)]
        public string Code;
        
        public Read() {
        }
        
        public Read(string Code) {
            this.Code = Code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/itemcategorycard", IsWrapped=true)]
    public partial class Read_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemcategorycard", Order=0)]
        public DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard ItemCategoryCard;
        
        public Read_Result() {
        }
        
        public Read_Result(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard ItemCategoryCard) {
            this.ItemCategoryCard = ItemCategoryCard;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/itemcategorycard", IsWrapped=true)]
    public partial class ReadByRecId {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemcategorycard", Order=0)]
        public string recId;
        
        public ReadByRecId() {
        }
        
        public ReadByRecId(string recId) {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/itemcategorycard", IsWrapped=true)]
    public partial class ReadByRecId_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemcategorycard", Order=0)]
        public DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard ItemCategoryCard;
        
        public ReadByRecId_Result() {
        }
        
        public ReadByRecId_Result(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard ItemCategoryCard) {
            this.ItemCategoryCard = ItemCategoryCard;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/itemcategorycard", IsWrapped=true)]
    public partial class ReadMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemcategorycard", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemcategorycard", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemcategorycard", Order=2)]
        public int setSize;
        
        public ReadMultiple() {
        }
        
        public ReadMultiple(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard_Filter[] filter, string bookmarkKey, int setSize) {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/itemcategorycard", IsWrapped=true)]
    public partial class ReadMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/itemcategorycard", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard[] ReadMultiple_Result1;
        
        public ReadMultiple_Result() {
        }
        
        public ReadMultiple_Result(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard[] ReadMultiple_Result1) {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/itemcategorycard", IsWrapped=true)]
    public partial class IsUpdated {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemcategorycard", Order=0)]
        public string Key;
        
        public IsUpdated() {
        }
        
        public IsUpdated(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/itemcategorycard", IsWrapped=true)]
    public partial class IsUpdated_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/itemcategorycard", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result() {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1) {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/itemcategorycard", IsWrapped=true)]
    public partial class GetRecIdFromKey {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemcategorycard", Order=0)]
        public string Key;
        
        public GetRecIdFromKey() {
        }
        
        public GetRecIdFromKey(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/itemcategorycard", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/itemcategorycard", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result() {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1) {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create", WrapperNamespace="urn:microsoft-dynamics-schemas/page/itemcategorycard", IsWrapped=true)]
    public partial class Create {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemcategorycard", Order=0)]
        public DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard ItemCategoryCard;
        
        public Create() {
        }
        
        public Create(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard ItemCategoryCard) {
            this.ItemCategoryCard = ItemCategoryCard;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/itemcategorycard", IsWrapped=true)]
    public partial class Create_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemcategorycard", Order=0)]
        public DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard ItemCategoryCard;
        
        public Create_Result() {
        }
        
        public Create_Result(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard ItemCategoryCard) {
            this.ItemCategoryCard = ItemCategoryCard;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/itemcategorycard", IsWrapped=true)]
    public partial class CreateMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemcategorycard", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard[] ItemCategoryCard_List;
        
        public CreateMultiple() {
        }
        
        public CreateMultiple(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard[] ItemCategoryCard_List) {
            this.ItemCategoryCard_List = ItemCategoryCard_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/itemcategorycard", IsWrapped=true)]
    public partial class CreateMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemcategorycard", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard[] ItemCategoryCard_List;
        
        public CreateMultiple_Result() {
        }
        
        public CreateMultiple_Result(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard[] ItemCategoryCard_List) {
            this.ItemCategoryCard_List = ItemCategoryCard_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="urn:microsoft-dynamics-schemas/page/itemcategorycard", IsWrapped=true)]
    public partial class Update {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemcategorycard", Order=0)]
        public DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard ItemCategoryCard;
        
        public Update() {
        }
        
        public Update(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard ItemCategoryCard) {
            this.ItemCategoryCard = ItemCategoryCard;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/itemcategorycard", IsWrapped=true)]
    public partial class Update_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemcategorycard", Order=0)]
        public DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard ItemCategoryCard;
        
        public Update_Result() {
        }
        
        public Update_Result(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard ItemCategoryCard) {
            this.ItemCategoryCard = ItemCategoryCard;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/itemcategorycard", IsWrapped=true)]
    public partial class UpdateMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemcategorycard", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard[] ItemCategoryCard_List;
        
        public UpdateMultiple() {
        }
        
        public UpdateMultiple(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard[] ItemCategoryCard_List) {
            this.ItemCategoryCard_List = ItemCategoryCard_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/itemcategorycard", IsWrapped=true)]
    public partial class UpdateMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemcategorycard", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard[] ItemCategoryCard_List;
        
        public UpdateMultiple_Result() {
        }
        
        public UpdateMultiple_Result(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard[] ItemCategoryCard_List) {
            this.ItemCategoryCard_List = ItemCategoryCard_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_Attributes", WrapperNamespace="urn:microsoft-dynamics-schemas/page/itemcategorycard", IsWrapped=true)]
    public partial class Delete_Attributes {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/itemcategorycard", Order=0)]
        public string Attributes_Key;
        
        public Delete_Attributes() {
        }
        
        public Delete_Attributes(string Attributes_Key) {
            this.Attributes_Key = Attributes_Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_Attributes_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/itemcategorycard", IsWrapped=true)]
    public partial class Delete_Attributes_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_Attributes_Result", Namespace="urn:microsoft-dynamics-schemas/page/itemcategorycard", Order=0)]
        public bool Delete_Attributes_Result1;
        
        public Delete_Attributes_Result() {
        }
        
        public Delete_Attributes_Result(bool Delete_Attributes_Result1) {
            this.Delete_Attributes_Result1 = Delete_Attributes_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ItemCategoryCard_PortChannel : DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ItemCategoryCard_PortClient : System.ServiceModel.ClientBase<DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard_Port>, DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard_Port {
        
        public ItemCategoryCard_PortClient() {
        }
        
        public ItemCategoryCard_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ItemCategoryCard_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ItemCategoryCard_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ItemCategoryCard_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.Read_Result DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard_Port.Read(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.Read request) {
            return base.Channel.Read(request);
        }
        
        public DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard Read(string Code) {
            DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.Read inValue = new DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.Read();
            inValue.Code = Code;
            DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.Read_Result retVal = ((DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard_Port)(this)).Read(inValue);
            return retVal.ItemCategoryCard;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.Read_Result> DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard_Port.ReadAsync(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.Read request) {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.Read_Result> ReadAsync(string Code) {
            DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.Read inValue = new DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.Read();
            inValue.Code = Code;
            return ((DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ReadByRecId_Result DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard_Port.ReadByRecId(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ReadByRecId request) {
            return base.Channel.ReadByRecId(request);
        }
        
        public DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard ReadByRecId(string recId) {
            DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ReadByRecId inValue = new DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ReadByRecId();
            inValue.recId = recId;
            DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ReadByRecId_Result retVal = ((DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard_Port)(this)).ReadByRecId(inValue);
            return retVal.ItemCategoryCard;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ReadByRecId_Result> DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard_Port.ReadByRecIdAsync(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ReadByRecId request) {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ReadByRecId_Result> ReadByRecIdAsync(string recId) {
            DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ReadByRecId inValue = new DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ReadByRecId();
            inValue.recId = recId;
            return ((DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ReadMultiple_Result DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard_Port.ReadMultiple(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ReadMultiple request) {
            return base.Channel.ReadMultiple(request);
        }
        
        public DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard[] ReadMultiple(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard_Filter[] filter, string bookmarkKey, int setSize) {
            DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ReadMultiple inValue = new DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ReadMultiple_Result retVal = ((DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard_Port)(this)).ReadMultiple(inValue);
            return retVal.ReadMultiple_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ReadMultiple_Result> DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard_Port.ReadMultipleAsync(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ReadMultiple request) {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ReadMultiple_Result> ReadMultipleAsync(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard_Filter[] filter, string bookmarkKey, int setSize) {
            DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ReadMultiple inValue = new DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.IsUpdated_Result DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard_Port.IsUpdated(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.IsUpdated request) {
            return base.Channel.IsUpdated(request);
        }
        
        public bool IsUpdated(string Key) {
            DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.IsUpdated inValue = new DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.IsUpdated();
            inValue.Key = Key;
            DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.IsUpdated_Result retVal = ((DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard_Port)(this)).IsUpdated(inValue);
            return retVal.IsUpdated_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.IsUpdated_Result> DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard_Port.IsUpdatedAsync(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.IsUpdated request) {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.IsUpdated_Result> IsUpdatedAsync(string Key) {
            DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.IsUpdated inValue = new DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.IsUpdated();
            inValue.Key = Key;
            return ((DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.GetRecIdFromKey_Result DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard_Port.GetRecIdFromKey(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKey(request);
        }
        
        public string GetRecIdFromKey(string Key) {
            DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.GetRecIdFromKey inValue = new DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.GetRecIdFromKey();
            inValue.Key = Key;
            DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.GetRecIdFromKey_Result retVal = ((DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard_Port)(this)).GetRecIdFromKey(inValue);
            return retVal.GetRecIdFromKey_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.GetRecIdFromKey_Result> DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard_Port.GetRecIdFromKeyAsync(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key) {
            DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.GetRecIdFromKey inValue = new DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.GetRecIdFromKey();
            inValue.Key = Key;
            return ((DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.Create_Result DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard_Port.Create(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.Create request) {
            return base.Channel.Create(request);
        }
        
        public void Create(ref DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard ItemCategoryCard) {
            DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.Create inValue = new DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.Create();
            inValue.ItemCategoryCard = ItemCategoryCard;
            DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.Create_Result retVal = ((DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard_Port)(this)).Create(inValue);
            ItemCategoryCard = retVal.ItemCategoryCard;
        }
        
        public System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.Create_Result> CreateAsync(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.Create request) {
            return base.Channel.CreateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.CreateMultiple_Result DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard_Port.CreateMultiple(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.CreateMultiple request) {
            return base.Channel.CreateMultiple(request);
        }
        
        public void CreateMultiple(ref DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard[] ItemCategoryCard_List) {
            DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.CreateMultiple inValue = new DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.CreateMultiple();
            inValue.ItemCategoryCard_List = ItemCategoryCard_List;
            DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.CreateMultiple_Result retVal = ((DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard_Port)(this)).CreateMultiple(inValue);
            ItemCategoryCard_List = retVal.ItemCategoryCard_List;
        }
        
        public System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.CreateMultiple_Result> CreateMultipleAsync(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.CreateMultiple request) {
            return base.Channel.CreateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.Update_Result DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard_Port.Update(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.Update request) {
            return base.Channel.Update(request);
        }
        
        public void Update(ref DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard ItemCategoryCard) {
            DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.Update inValue = new DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.Update();
            inValue.ItemCategoryCard = ItemCategoryCard;
            DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.Update_Result retVal = ((DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard_Port)(this)).Update(inValue);
            ItemCategoryCard = retVal.ItemCategoryCard;
        }
        
        public System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.Update_Result> UpdateAsync(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.Update request) {
            return base.Channel.UpdateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.UpdateMultiple_Result DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard_Port.UpdateMultiple(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.UpdateMultiple request) {
            return base.Channel.UpdateMultiple(request);
        }
        
        public void UpdateMultiple(ref DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard[] ItemCategoryCard_List) {
            DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.UpdateMultiple inValue = new DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.UpdateMultiple();
            inValue.ItemCategoryCard_List = ItemCategoryCard_List;
            DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.UpdateMultiple_Result retVal = ((DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard_Port)(this)).UpdateMultiple(inValue);
            ItemCategoryCard_List = retVal.ItemCategoryCard_List;
        }
        
        public System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.UpdateMultiple_Result> UpdateMultipleAsync(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.UpdateMultiple request) {
            return base.Channel.UpdateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.Delete_Attributes_Result DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard_Port.Delete_Attributes(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.Delete_Attributes request) {
            return base.Channel.Delete_Attributes(request);
        }
        
        public bool Delete_Attributes(string Attributes_Key) {
            DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.Delete_Attributes inValue = new DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.Delete_Attributes();
            inValue.Attributes_Key = Attributes_Key;
            DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.Delete_Attributes_Result retVal = ((DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard_Port)(this)).Delete_Attributes(inValue);
            return retVal.Delete_Attributes_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.Delete_Attributes_Result> DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard_Port.Delete_AttributesAsync(DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.Delete_Attributes request) {
            return base.Channel.Delete_AttributesAsync(request);
        }
        
        public System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.Delete_Attributes_Result> Delete_AttributesAsync(string Attributes_Key) {
            DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.Delete_Attributes inValue = new DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.Delete_Attributes();
            inValue.Attributes_Key = Attributes_Key;
            return ((DynamicsNav.WebserviceTests.SOAP.ItemCategoryCard.ItemCategoryCard_Port)(this)).Delete_AttributesAsync(inValue);
        }
    }
}
