//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicsNav.WebserviceTests.SOAP.BOMs {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/boms", ConfigurationName="SOAP.BOMs.BOMs_Port")]
    public interface BOMs_Port {
        
        // CODEGEN: Generating message contract since the wrapper name (Read_Result) of message Read_Result does not match the default value (Read)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/boms:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DynamicsNav.WebserviceTests.SOAP.BOMs.Read_Result Read(DynamicsNav.WebserviceTests.SOAP.BOMs.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/boms:Read", ReplyAction="*")]
        System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.BOMs.Read_Result> ReadAsync(DynamicsNav.WebserviceTests.SOAP.BOMs.Read request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadByRecId_Result) of message ReadByRecId_Result does not match the default value (ReadByRecId)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/boms:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DynamicsNav.WebserviceTests.SOAP.BOMs.ReadByRecId_Result ReadByRecId(DynamicsNav.WebserviceTests.SOAP.BOMs.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/boms:ReadByRecId", ReplyAction="*")]
        System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.BOMs.ReadByRecId_Result> ReadByRecIdAsync(DynamicsNav.WebserviceTests.SOAP.BOMs.ReadByRecId request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadMultiple_Result) of message ReadMultiple_Result does not match the default value (ReadMultiple)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/boms:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DynamicsNav.WebserviceTests.SOAP.BOMs.ReadMultiple_Result ReadMultiple(DynamicsNav.WebserviceTests.SOAP.BOMs.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/boms:ReadMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.BOMs.ReadMultiple_Result> ReadMultipleAsync(DynamicsNav.WebserviceTests.SOAP.BOMs.ReadMultiple request);
        
        // CODEGEN: Generating message contract since the wrapper name (IsUpdated_Result) of message IsUpdated_Result does not match the default value (IsUpdated)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/boms:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DynamicsNav.WebserviceTests.SOAP.BOMs.IsUpdated_Result IsUpdated(DynamicsNav.WebserviceTests.SOAP.BOMs.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/boms:IsUpdated", ReplyAction="*")]
        System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.BOMs.IsUpdated_Result> IsUpdatedAsync(DynamicsNav.WebserviceTests.SOAP.BOMs.IsUpdated request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetRecIdFromKey_Result) of message GetRecIdFromKey_Result does not match the default value (GetRecIdFromKey)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/boms:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DynamicsNav.WebserviceTests.SOAP.BOMs.GetRecIdFromKey_Result GetRecIdFromKey(DynamicsNav.WebserviceTests.SOAP.BOMs.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/boms:GetRecIdFromKey", ReplyAction="*")]
        System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.BOMs.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(DynamicsNav.WebserviceTests.SOAP.BOMs.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/boms:Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DynamicsNav.WebserviceTests.SOAP.BOMs.Create_Result Create(DynamicsNav.WebserviceTests.SOAP.BOMs.Create request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/boms:Create", ReplyAction="*")]
        System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.BOMs.Create_Result> CreateAsync(DynamicsNav.WebserviceTests.SOAP.BOMs.Create request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/boms:CreateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DynamicsNav.WebserviceTests.SOAP.BOMs.CreateMultiple_Result CreateMultiple(DynamicsNav.WebserviceTests.SOAP.BOMs.CreateMultiple request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/boms:CreateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.BOMs.CreateMultiple_Result> CreateMultipleAsync(DynamicsNav.WebserviceTests.SOAP.BOMs.CreateMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/boms:Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DynamicsNav.WebserviceTests.SOAP.BOMs.Update_Result Update(DynamicsNav.WebserviceTests.SOAP.BOMs.Update request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/boms:Update", ReplyAction="*")]
        System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.BOMs.Update_Result> UpdateAsync(DynamicsNav.WebserviceTests.SOAP.BOMs.Update request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/boms:UpdateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DynamicsNav.WebserviceTests.SOAP.BOMs.UpdateMultiple_Result UpdateMultiple(DynamicsNav.WebserviceTests.SOAP.BOMs.UpdateMultiple request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/boms:UpdateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.BOMs.UpdateMultiple_Result> UpdateMultipleAsync(DynamicsNav.WebserviceTests.SOAP.BOMs.UpdateMultiple request);
        
        // CODEGEN: Generating message contract since the wrapper name (Delete_Result) of message Delete_Result does not match the default value (Delete)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/boms:Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DynamicsNav.WebserviceTests.SOAP.BOMs.Delete_Result Delete(DynamicsNav.WebserviceTests.SOAP.BOMs.Delete request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/boms:Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.BOMs.Delete_Result> DeleteAsync(DynamicsNav.WebserviceTests.SOAP.BOMs.Delete request);
        
        // CODEGEN: Generating message contract since the wrapper name (Delete_ProdBOMLine_Result) of message Delete_ProdBOMLine_Result does not match the default value (Delete_ProdBOMLine)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/boms:Delete_ProdBOMLine", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DynamicsNav.WebserviceTests.SOAP.BOMs.Delete_ProdBOMLine_Result Delete_ProdBOMLine(DynamicsNav.WebserviceTests.SOAP.BOMs.Delete_ProdBOMLine request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/boms:Delete_ProdBOMLine", ReplyAction="*")]
        System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.BOMs.Delete_ProdBOMLine_Result> Delete_ProdBOMLineAsync(DynamicsNav.WebserviceTests.SOAP.BOMs.Delete_ProdBOMLine request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/boms")]
    public partial class BOMs : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string noField;
        
        private string descriptionField;
        
        private string unit_of_Measure_CodeField;
        
        private Status statusField;
        
        private bool statusFieldSpecified;
        
        private string search_NameField;
        
        private string version_NosField;
        
        private string activeVersionCodeField;
        
        private System.DateTime last_Date_ModifiedField;
        
        private bool last_Date_ModifiedFieldSpecified;
        
        private Production_BOM_Lines[] prodBOMLineField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
                this.RaisePropertyChanged("No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Unit_of_Measure_Code {
            get {
                return this.unit_of_Measure_CodeField;
            }
            set {
                this.unit_of_Measure_CodeField = value;
                this.RaisePropertyChanged("Unit_of_Measure_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public Status Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
                this.RaisePropertyChanged("StatusSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Search_Name {
            get {
                return this.search_NameField;
            }
            set {
                this.search_NameField = value;
                this.RaisePropertyChanged("Search_Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Version_Nos {
            get {
                return this.version_NosField;
            }
            set {
                this.version_NosField = value;
                this.RaisePropertyChanged("Version_Nos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ActiveVersionCode {
            get {
                return this.activeVersionCodeField;
            }
            set {
                this.activeVersionCodeField = value;
                this.RaisePropertyChanged("ActiveVersionCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=8)]
        public System.DateTime Last_Date_Modified {
            get {
                return this.last_Date_ModifiedField;
            }
            set {
                this.last_Date_ModifiedField = value;
                this.RaisePropertyChanged("Last_Date_Modified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Last_Date_ModifiedSpecified {
            get {
                return this.last_Date_ModifiedFieldSpecified;
            }
            set {
                this.last_Date_ModifiedFieldSpecified = value;
                this.RaisePropertyChanged("Last_Date_ModifiedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=9)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Production_BOM_Lines[] ProdBOMLine {
            get {
                return this.prodBOMLineField;
            }
            set {
                this.prodBOMLineField = value;
                this.RaisePropertyChanged("ProdBOMLine");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/boms")]
    public enum Status {
        
        /// <remarks/>
        New,
        
        /// <remarks/>
        Certified,
        
        /// <remarks/>
        Under_Development,
        
        /// <remarks/>
        Closed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/boms")]
    public partial class Production_BOM_Lines : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private Type typeField;
        
        private bool typeFieldSpecified;
        
        private string noField;
        
        private string variant_CodeField;
        
        private string descriptionField;
        
        private Calculation_Formula calculation_FormulaField;
        
        private bool calculation_FormulaFieldSpecified;
        
        private decimal lengthField;
        
        private bool lengthFieldSpecified;
        
        private decimal widthField;
        
        private bool widthFieldSpecified;
        
        private decimal depthField;
        
        private bool depthFieldSpecified;
        
        private decimal weightField;
        
        private bool weightFieldSpecified;
        
        private decimal quantity_perField;
        
        private bool quantity_perFieldSpecified;
        
        private string unit_of_Measure_CodeField;
        
        private decimal scrap_PercentField;
        
        private bool scrap_PercentFieldSpecified;
        
        private string routing_Link_CodeField;
        
        private string positionField;
        
        private string position_2Field;
        
        private string position_3Field;
        
        private string lead_Time_OffsetField;
        
        private System.DateTime starting_DateField;
        
        private bool starting_DateFieldSpecified;
        
        private System.DateTime ending_DateField;
        
        private bool ending_DateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Type Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
                this.RaisePropertyChanged("TypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
                this.RaisePropertyChanged("No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Variant_Code {
            get {
                return this.variant_CodeField;
            }
            set {
                this.variant_CodeField = value;
                this.RaisePropertyChanged("Variant_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public Calculation_Formula Calculation_Formula {
            get {
                return this.calculation_FormulaField;
            }
            set {
                this.calculation_FormulaField = value;
                this.RaisePropertyChanged("Calculation_Formula");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Calculation_FormulaSpecified {
            get {
                return this.calculation_FormulaFieldSpecified;
            }
            set {
                this.calculation_FormulaFieldSpecified = value;
                this.RaisePropertyChanged("Calculation_FormulaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public decimal Length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
                this.RaisePropertyChanged("Length");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LengthSpecified {
            get {
                return this.lengthFieldSpecified;
            }
            set {
                this.lengthFieldSpecified = value;
                this.RaisePropertyChanged("LengthSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public decimal Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
                this.RaisePropertyChanged("Width");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WidthSpecified {
            get {
                return this.widthFieldSpecified;
            }
            set {
                this.widthFieldSpecified = value;
                this.RaisePropertyChanged("WidthSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public decimal Depth {
            get {
                return this.depthField;
            }
            set {
                this.depthField = value;
                this.RaisePropertyChanged("Depth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DepthSpecified {
            get {
                return this.depthFieldSpecified;
            }
            set {
                this.depthFieldSpecified = value;
                this.RaisePropertyChanged("DepthSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public decimal Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
                this.RaisePropertyChanged("Weight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WeightSpecified {
            get {
                return this.weightFieldSpecified;
            }
            set {
                this.weightFieldSpecified = value;
                this.RaisePropertyChanged("WeightSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public decimal Quantity_per {
            get {
                return this.quantity_perField;
            }
            set {
                this.quantity_perField = value;
                this.RaisePropertyChanged("Quantity_per");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Quantity_perSpecified {
            get {
                return this.quantity_perFieldSpecified;
            }
            set {
                this.quantity_perFieldSpecified = value;
                this.RaisePropertyChanged("Quantity_perSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Unit_of_Measure_Code {
            get {
                return this.unit_of_Measure_CodeField;
            }
            set {
                this.unit_of_Measure_CodeField = value;
                this.RaisePropertyChanged("Unit_of_Measure_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public decimal Scrap_Percent {
            get {
                return this.scrap_PercentField;
            }
            set {
                this.scrap_PercentField = value;
                this.RaisePropertyChanged("Scrap_Percent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Scrap_PercentSpecified {
            get {
                return this.scrap_PercentFieldSpecified;
            }
            set {
                this.scrap_PercentFieldSpecified = value;
                this.RaisePropertyChanged("Scrap_PercentSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Routing_Link_Code {
            get {
                return this.routing_Link_CodeField;
            }
            set {
                this.routing_Link_CodeField = value;
                this.RaisePropertyChanged("Routing_Link_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
                this.RaisePropertyChanged("Position");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Position_2 {
            get {
                return this.position_2Field;
            }
            set {
                this.position_2Field = value;
                this.RaisePropertyChanged("Position_2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Position_3 {
            get {
                return this.position_3Field;
            }
            set {
                this.position_3Field = value;
                this.RaisePropertyChanged("Position_3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string Lead_Time_Offset {
            get {
                return this.lead_Time_OffsetField;
            }
            set {
                this.lead_Time_OffsetField = value;
                this.RaisePropertyChanged("Lead_Time_Offset");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=18)]
        public System.DateTime Starting_Date {
            get {
                return this.starting_DateField;
            }
            set {
                this.starting_DateField = value;
                this.RaisePropertyChanged("Starting_Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Starting_DateSpecified {
            get {
                return this.starting_DateFieldSpecified;
            }
            set {
                this.starting_DateFieldSpecified = value;
                this.RaisePropertyChanged("Starting_DateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=19)]
        public System.DateTime Ending_Date {
            get {
                return this.ending_DateField;
            }
            set {
                this.ending_DateField = value;
                this.RaisePropertyChanged("Ending_Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Ending_DateSpecified {
            get {
                return this.ending_DateFieldSpecified;
            }
            set {
                this.ending_DateFieldSpecified = value;
                this.RaisePropertyChanged("Ending_DateSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/boms")]
    public enum Type {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Item,
        
        /// <remarks/>
        Production_BOM,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/boms")]
    public enum Calculation_Formula {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Length,
        
        /// <remarks/>
        Length__x002A__Width,
        
        /// <remarks/>
        Length__x002A__Width__x002A__Depth,
        
        /// <remarks/>
        Weight,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/boms")]
    public partial class BOMs_Filter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private BOMs_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public BOMs_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
                this.RaisePropertyChanged("Criteria");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/boms")]
    public enum BOMs_Fields {
        
        /// <remarks/>
        No,
        
        /// <remarks/>
        Description,
        
        /// <remarks/>
        Unit_of_Measure_Code,
        
        /// <remarks/>
        Status,
        
        /// <remarks/>
        Search_Name,
        
        /// <remarks/>
        Version_Nos,
        
        /// <remarks/>
        ActiveVersionCode,
        
        /// <remarks/>
        Last_Date_Modified,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/boms", IsWrapped=true)]
    public partial class Read {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/boms", Order=0)]
        public string No;
        
        public Read() {
        }
        
        public Read(string No) {
            this.No = No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/boms", IsWrapped=true)]
    public partial class Read_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/boms", Order=0)]
        public DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs BOMs;
        
        public Read_Result() {
        }
        
        public Read_Result(DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs BOMs) {
            this.BOMs = BOMs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/boms", IsWrapped=true)]
    public partial class ReadByRecId {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/boms", Order=0)]
        public string recId;
        
        public ReadByRecId() {
        }
        
        public ReadByRecId(string recId) {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/boms", IsWrapped=true)]
    public partial class ReadByRecId_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/boms", Order=0)]
        public DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs BOMs;
        
        public ReadByRecId_Result() {
        }
        
        public ReadByRecId_Result(DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs BOMs) {
            this.BOMs = BOMs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/boms", IsWrapped=true)]
    public partial class ReadMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/boms", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/boms", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/boms", Order=2)]
        public int setSize;
        
        public ReadMultiple() {
        }
        
        public ReadMultiple(DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs_Filter[] filter, string bookmarkKey, int setSize) {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/boms", IsWrapped=true)]
    public partial class ReadMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/boms", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs[] ReadMultiple_Result1;
        
        public ReadMultiple_Result() {
        }
        
        public ReadMultiple_Result(DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs[] ReadMultiple_Result1) {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/boms", IsWrapped=true)]
    public partial class IsUpdated {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/boms", Order=0)]
        public string Key;
        
        public IsUpdated() {
        }
        
        public IsUpdated(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/boms", IsWrapped=true)]
    public partial class IsUpdated_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/boms", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result() {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1) {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/boms", IsWrapped=true)]
    public partial class GetRecIdFromKey {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/boms", Order=0)]
        public string Key;
        
        public GetRecIdFromKey() {
        }
        
        public GetRecIdFromKey(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/boms", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/boms", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result() {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1) {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create", WrapperNamespace="urn:microsoft-dynamics-schemas/page/boms", IsWrapped=true)]
    public partial class Create {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/boms", Order=0)]
        public DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs BOMs;
        
        public Create() {
        }
        
        public Create(DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs BOMs) {
            this.BOMs = BOMs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/boms", IsWrapped=true)]
    public partial class Create_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/boms", Order=0)]
        public DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs BOMs;
        
        public Create_Result() {
        }
        
        public Create_Result(DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs BOMs) {
            this.BOMs = BOMs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/boms", IsWrapped=true)]
    public partial class CreateMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/boms", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs[] BOMs_List;
        
        public CreateMultiple() {
        }
        
        public CreateMultiple(DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs[] BOMs_List) {
            this.BOMs_List = BOMs_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/boms", IsWrapped=true)]
    public partial class CreateMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/boms", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs[] BOMs_List;
        
        public CreateMultiple_Result() {
        }
        
        public CreateMultiple_Result(DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs[] BOMs_List) {
            this.BOMs_List = BOMs_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="urn:microsoft-dynamics-schemas/page/boms", IsWrapped=true)]
    public partial class Update {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/boms", Order=0)]
        public DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs BOMs;
        
        public Update() {
        }
        
        public Update(DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs BOMs) {
            this.BOMs = BOMs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/boms", IsWrapped=true)]
    public partial class Update_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/boms", Order=0)]
        public DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs BOMs;
        
        public Update_Result() {
        }
        
        public Update_Result(DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs BOMs) {
            this.BOMs = BOMs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/boms", IsWrapped=true)]
    public partial class UpdateMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/boms", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs[] BOMs_List;
        
        public UpdateMultiple() {
        }
        
        public UpdateMultiple(DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs[] BOMs_List) {
            this.BOMs_List = BOMs_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/boms", IsWrapped=true)]
    public partial class UpdateMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/boms", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs[] BOMs_List;
        
        public UpdateMultiple_Result() {
        }
        
        public UpdateMultiple_Result(DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs[] BOMs_List) {
            this.BOMs_List = BOMs_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete", WrapperNamespace="urn:microsoft-dynamics-schemas/page/boms", IsWrapped=true)]
    public partial class Delete {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/boms", Order=0)]
        public string Key;
        
        public Delete() {
        }
        
        public Delete(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/boms", IsWrapped=true)]
    public partial class Delete_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_Result", Namespace="urn:microsoft-dynamics-schemas/page/boms", Order=0)]
        public bool Delete_Result1;
        
        public Delete_Result() {
        }
        
        public Delete_Result(bool Delete_Result1) {
            this.Delete_Result1 = Delete_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_ProdBOMLine", WrapperNamespace="urn:microsoft-dynamics-schemas/page/boms", IsWrapped=true)]
    public partial class Delete_ProdBOMLine {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/boms", Order=0)]
        public string ProdBOMLine_Key;
        
        public Delete_ProdBOMLine() {
        }
        
        public Delete_ProdBOMLine(string ProdBOMLine_Key) {
            this.ProdBOMLine_Key = ProdBOMLine_Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_ProdBOMLine_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/boms", IsWrapped=true)]
    public partial class Delete_ProdBOMLine_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_ProdBOMLine_Result", Namespace="urn:microsoft-dynamics-schemas/page/boms", Order=0)]
        public bool Delete_ProdBOMLine_Result1;
        
        public Delete_ProdBOMLine_Result() {
        }
        
        public Delete_ProdBOMLine_Result(bool Delete_ProdBOMLine_Result1) {
            this.Delete_ProdBOMLine_Result1 = Delete_ProdBOMLine_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BOMs_PortChannel : DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BOMs_PortClient : System.ServiceModel.ClientBase<DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs_Port>, DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs_Port {
        
        public BOMs_PortClient() {
        }
        
        public BOMs_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BOMs_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BOMs_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BOMs_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DynamicsNav.WebserviceTests.SOAP.BOMs.Read_Result DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs_Port.Read(DynamicsNav.WebserviceTests.SOAP.BOMs.Read request) {
            return base.Channel.Read(request);
        }
        
        public DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs Read(string No) {
            DynamicsNav.WebserviceTests.SOAP.BOMs.Read inValue = new DynamicsNav.WebserviceTests.SOAP.BOMs.Read();
            inValue.No = No;
            DynamicsNav.WebserviceTests.SOAP.BOMs.Read_Result retVal = ((DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs_Port)(this)).Read(inValue);
            return retVal.BOMs;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.BOMs.Read_Result> DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs_Port.ReadAsync(DynamicsNav.WebserviceTests.SOAP.BOMs.Read request) {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.BOMs.Read_Result> ReadAsync(string No) {
            DynamicsNav.WebserviceTests.SOAP.BOMs.Read inValue = new DynamicsNav.WebserviceTests.SOAP.BOMs.Read();
            inValue.No = No;
            return ((DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DynamicsNav.WebserviceTests.SOAP.BOMs.ReadByRecId_Result DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs_Port.ReadByRecId(DynamicsNav.WebserviceTests.SOAP.BOMs.ReadByRecId request) {
            return base.Channel.ReadByRecId(request);
        }
        
        public DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs ReadByRecId(string recId) {
            DynamicsNav.WebserviceTests.SOAP.BOMs.ReadByRecId inValue = new DynamicsNav.WebserviceTests.SOAP.BOMs.ReadByRecId();
            inValue.recId = recId;
            DynamicsNav.WebserviceTests.SOAP.BOMs.ReadByRecId_Result retVal = ((DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs_Port)(this)).ReadByRecId(inValue);
            return retVal.BOMs;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.BOMs.ReadByRecId_Result> DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs_Port.ReadByRecIdAsync(DynamicsNav.WebserviceTests.SOAP.BOMs.ReadByRecId request) {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.BOMs.ReadByRecId_Result> ReadByRecIdAsync(string recId) {
            DynamicsNav.WebserviceTests.SOAP.BOMs.ReadByRecId inValue = new DynamicsNav.WebserviceTests.SOAP.BOMs.ReadByRecId();
            inValue.recId = recId;
            return ((DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DynamicsNav.WebserviceTests.SOAP.BOMs.ReadMultiple_Result DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs_Port.ReadMultiple(DynamicsNav.WebserviceTests.SOAP.BOMs.ReadMultiple request) {
            return base.Channel.ReadMultiple(request);
        }
        
        public DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs[] ReadMultiple(DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs_Filter[] filter, string bookmarkKey, int setSize) {
            DynamicsNav.WebserviceTests.SOAP.BOMs.ReadMultiple inValue = new DynamicsNav.WebserviceTests.SOAP.BOMs.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            DynamicsNav.WebserviceTests.SOAP.BOMs.ReadMultiple_Result retVal = ((DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs_Port)(this)).ReadMultiple(inValue);
            return retVal.ReadMultiple_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.BOMs.ReadMultiple_Result> DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs_Port.ReadMultipleAsync(DynamicsNav.WebserviceTests.SOAP.BOMs.ReadMultiple request) {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.BOMs.ReadMultiple_Result> ReadMultipleAsync(DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs_Filter[] filter, string bookmarkKey, int setSize) {
            DynamicsNav.WebserviceTests.SOAP.BOMs.ReadMultiple inValue = new DynamicsNav.WebserviceTests.SOAP.BOMs.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DynamicsNav.WebserviceTests.SOAP.BOMs.IsUpdated_Result DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs_Port.IsUpdated(DynamicsNav.WebserviceTests.SOAP.BOMs.IsUpdated request) {
            return base.Channel.IsUpdated(request);
        }
        
        public bool IsUpdated(string Key) {
            DynamicsNav.WebserviceTests.SOAP.BOMs.IsUpdated inValue = new DynamicsNav.WebserviceTests.SOAP.BOMs.IsUpdated();
            inValue.Key = Key;
            DynamicsNav.WebserviceTests.SOAP.BOMs.IsUpdated_Result retVal = ((DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs_Port)(this)).IsUpdated(inValue);
            return retVal.IsUpdated_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.BOMs.IsUpdated_Result> DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs_Port.IsUpdatedAsync(DynamicsNav.WebserviceTests.SOAP.BOMs.IsUpdated request) {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.BOMs.IsUpdated_Result> IsUpdatedAsync(string Key) {
            DynamicsNav.WebserviceTests.SOAP.BOMs.IsUpdated inValue = new DynamicsNav.WebserviceTests.SOAP.BOMs.IsUpdated();
            inValue.Key = Key;
            return ((DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DynamicsNav.WebserviceTests.SOAP.BOMs.GetRecIdFromKey_Result DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs_Port.GetRecIdFromKey(DynamicsNav.WebserviceTests.SOAP.BOMs.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKey(request);
        }
        
        public string GetRecIdFromKey(string Key) {
            DynamicsNav.WebserviceTests.SOAP.BOMs.GetRecIdFromKey inValue = new DynamicsNav.WebserviceTests.SOAP.BOMs.GetRecIdFromKey();
            inValue.Key = Key;
            DynamicsNav.WebserviceTests.SOAP.BOMs.GetRecIdFromKey_Result retVal = ((DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs_Port)(this)).GetRecIdFromKey(inValue);
            return retVal.GetRecIdFromKey_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.BOMs.GetRecIdFromKey_Result> DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs_Port.GetRecIdFromKeyAsync(DynamicsNav.WebserviceTests.SOAP.BOMs.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.BOMs.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key) {
            DynamicsNav.WebserviceTests.SOAP.BOMs.GetRecIdFromKey inValue = new DynamicsNav.WebserviceTests.SOAP.BOMs.GetRecIdFromKey();
            inValue.Key = Key;
            return ((DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DynamicsNav.WebserviceTests.SOAP.BOMs.Create_Result DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs_Port.Create(DynamicsNav.WebserviceTests.SOAP.BOMs.Create request) {
            return base.Channel.Create(request);
        }
        
        public void Create(ref DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs BOMs) {
            DynamicsNav.WebserviceTests.SOAP.BOMs.Create inValue = new DynamicsNav.WebserviceTests.SOAP.BOMs.Create();
            inValue.BOMs = BOMs;
            DynamicsNav.WebserviceTests.SOAP.BOMs.Create_Result retVal = ((DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs_Port)(this)).Create(inValue);
            BOMs = retVal.BOMs;
        }
        
        public System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.BOMs.Create_Result> CreateAsync(DynamicsNav.WebserviceTests.SOAP.BOMs.Create request) {
            return base.Channel.CreateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DynamicsNav.WebserviceTests.SOAP.BOMs.CreateMultiple_Result DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs_Port.CreateMultiple(DynamicsNav.WebserviceTests.SOAP.BOMs.CreateMultiple request) {
            return base.Channel.CreateMultiple(request);
        }
        
        public void CreateMultiple(ref DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs[] BOMs_List) {
            DynamicsNav.WebserviceTests.SOAP.BOMs.CreateMultiple inValue = new DynamicsNav.WebserviceTests.SOAP.BOMs.CreateMultiple();
            inValue.BOMs_List = BOMs_List;
            DynamicsNav.WebserviceTests.SOAP.BOMs.CreateMultiple_Result retVal = ((DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs_Port)(this)).CreateMultiple(inValue);
            BOMs_List = retVal.BOMs_List;
        }
        
        public System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.BOMs.CreateMultiple_Result> CreateMultipleAsync(DynamicsNav.WebserviceTests.SOAP.BOMs.CreateMultiple request) {
            return base.Channel.CreateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DynamicsNav.WebserviceTests.SOAP.BOMs.Update_Result DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs_Port.Update(DynamicsNav.WebserviceTests.SOAP.BOMs.Update request) {
            return base.Channel.Update(request);
        }
        
        public void Update(ref DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs BOMs) {
            DynamicsNav.WebserviceTests.SOAP.BOMs.Update inValue = new DynamicsNav.WebserviceTests.SOAP.BOMs.Update();
            inValue.BOMs = BOMs;
            DynamicsNav.WebserviceTests.SOAP.BOMs.Update_Result retVal = ((DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs_Port)(this)).Update(inValue);
            BOMs = retVal.BOMs;
        }
        
        public System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.BOMs.Update_Result> UpdateAsync(DynamicsNav.WebserviceTests.SOAP.BOMs.Update request) {
            return base.Channel.UpdateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DynamicsNav.WebserviceTests.SOAP.BOMs.UpdateMultiple_Result DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs_Port.UpdateMultiple(DynamicsNav.WebserviceTests.SOAP.BOMs.UpdateMultiple request) {
            return base.Channel.UpdateMultiple(request);
        }
        
        public void UpdateMultiple(ref DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs[] BOMs_List) {
            DynamicsNav.WebserviceTests.SOAP.BOMs.UpdateMultiple inValue = new DynamicsNav.WebserviceTests.SOAP.BOMs.UpdateMultiple();
            inValue.BOMs_List = BOMs_List;
            DynamicsNav.WebserviceTests.SOAP.BOMs.UpdateMultiple_Result retVal = ((DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs_Port)(this)).UpdateMultiple(inValue);
            BOMs_List = retVal.BOMs_List;
        }
        
        public System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.BOMs.UpdateMultiple_Result> UpdateMultipleAsync(DynamicsNav.WebserviceTests.SOAP.BOMs.UpdateMultiple request) {
            return base.Channel.UpdateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DynamicsNav.WebserviceTests.SOAP.BOMs.Delete_Result DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs_Port.Delete(DynamicsNav.WebserviceTests.SOAP.BOMs.Delete request) {
            return base.Channel.Delete(request);
        }
        
        public bool Delete(string Key) {
            DynamicsNav.WebserviceTests.SOAP.BOMs.Delete inValue = new DynamicsNav.WebserviceTests.SOAP.BOMs.Delete();
            inValue.Key = Key;
            DynamicsNav.WebserviceTests.SOAP.BOMs.Delete_Result retVal = ((DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs_Port)(this)).Delete(inValue);
            return retVal.Delete_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.BOMs.Delete_Result> DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs_Port.DeleteAsync(DynamicsNav.WebserviceTests.SOAP.BOMs.Delete request) {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.BOMs.Delete_Result> DeleteAsync(string Key) {
            DynamicsNav.WebserviceTests.SOAP.BOMs.Delete inValue = new DynamicsNav.WebserviceTests.SOAP.BOMs.Delete();
            inValue.Key = Key;
            return ((DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs_Port)(this)).DeleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DynamicsNav.WebserviceTests.SOAP.BOMs.Delete_ProdBOMLine_Result DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs_Port.Delete_ProdBOMLine(DynamicsNav.WebserviceTests.SOAP.BOMs.Delete_ProdBOMLine request) {
            return base.Channel.Delete_ProdBOMLine(request);
        }
        
        public bool Delete_ProdBOMLine(string ProdBOMLine_Key) {
            DynamicsNav.WebserviceTests.SOAP.BOMs.Delete_ProdBOMLine inValue = new DynamicsNav.WebserviceTests.SOAP.BOMs.Delete_ProdBOMLine();
            inValue.ProdBOMLine_Key = ProdBOMLine_Key;
            DynamicsNav.WebserviceTests.SOAP.BOMs.Delete_ProdBOMLine_Result retVal = ((DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs_Port)(this)).Delete_ProdBOMLine(inValue);
            return retVal.Delete_ProdBOMLine_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.BOMs.Delete_ProdBOMLine_Result> DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs_Port.Delete_ProdBOMLineAsync(DynamicsNav.WebserviceTests.SOAP.BOMs.Delete_ProdBOMLine request) {
            return base.Channel.Delete_ProdBOMLineAsync(request);
        }
        
        public System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.BOMs.Delete_ProdBOMLine_Result> Delete_ProdBOMLineAsync(string ProdBOMLine_Key) {
            DynamicsNav.WebserviceTests.SOAP.BOMs.Delete_ProdBOMLine inValue = new DynamicsNav.WebserviceTests.SOAP.BOMs.Delete_ProdBOMLine();
            inValue.ProdBOMLine_Key = ProdBOMLine_Key;
            return ((DynamicsNav.WebserviceTests.SOAP.BOMs.BOMs_Port)(this)).Delete_ProdBOMLineAsync(inValue);
        }
    }
}
