//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicsNav.WebserviceTests.SOAP.NoSeriesLines {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/noserieslines", ConfigurationName="SOAP.NoSeriesLines.NoSeriesLines_Port")]
    public interface NoSeriesLines_Port {
        
        // CODEGEN: Generating message contract since the wrapper name (Read_Result) of message Read_Result does not match the default value (Read)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/noserieslines:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.Read_Result Read(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/noserieslines:Read", ReplyAction="*")]
        System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.Read_Result> ReadAsync(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.Read request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadByRecId_Result) of message ReadByRecId_Result does not match the default value (ReadByRecId)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/noserieslines:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.ReadByRecId_Result ReadByRecId(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/noserieslines:ReadByRecId", ReplyAction="*")]
        System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.ReadByRecId_Result> ReadByRecIdAsync(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.ReadByRecId request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadMultiple_Result) of message ReadMultiple_Result does not match the default value (ReadMultiple)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/noserieslines:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.ReadMultiple_Result ReadMultiple(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/noserieslines:ReadMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.ReadMultiple_Result> ReadMultipleAsync(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.ReadMultiple request);
        
        // CODEGEN: Generating message contract since the wrapper name (IsUpdated_Result) of message IsUpdated_Result does not match the default value (IsUpdated)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/noserieslines:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.IsUpdated_Result IsUpdated(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/noserieslines:IsUpdated", ReplyAction="*")]
        System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.IsUpdated_Result> IsUpdatedAsync(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.IsUpdated request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetRecIdFromKey_Result) of message GetRecIdFromKey_Result does not match the default value (GetRecIdFromKey)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/noserieslines:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.GetRecIdFromKey_Result GetRecIdFromKey(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/noserieslines:GetRecIdFromKey", ReplyAction="*")]
        System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/noserieslines:Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.Create_Result Create(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.Create request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/noserieslines:Create", ReplyAction="*")]
        System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.Create_Result> CreateAsync(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.Create request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/noserieslines:CreateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.CreateMultiple_Result CreateMultiple(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.CreateMultiple request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/noserieslines:CreateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.CreateMultiple_Result> CreateMultipleAsync(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.CreateMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/noserieslines:Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.Update_Result Update(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.Update request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/noserieslines:Update", ReplyAction="*")]
        System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.Update_Result> UpdateAsync(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.Update request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/noserieslines:UpdateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.UpdateMultiple_Result UpdateMultiple(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.UpdateMultiple request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/noserieslines:UpdateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.UpdateMultiple_Result> UpdateMultipleAsync(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.UpdateMultiple request);
        
        // CODEGEN: Generating message contract since the wrapper name (Delete_Result) of message Delete_Result does not match the default value (Delete)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/noserieslines:Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.Delete_Result Delete(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.Delete request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/noserieslines:Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.Delete_Result> DeleteAsync(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.Delete request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/noserieslines")]
    public partial class NoSeriesLines : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string series_CodeField;
        
        private System.DateTime starting_DateField;
        
        private bool starting_DateFieldSpecified;
        
        private string starting_NoField;
        
        private string ending_NoField;
        
        private System.DateTime last_Date_UsedField;
        
        private bool last_Date_UsedFieldSpecified;
        
        private string last_No_UsedField;
        
        private string warning_NoField;
        
        private int increment_by_NoField;
        
        private bool increment_by_NoFieldSpecified;
        
        private bool openField;
        
        private bool openFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Series_Code {
            get {
                return this.series_CodeField;
            }
            set {
                this.series_CodeField = value;
                this.RaisePropertyChanged("Series_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        public System.DateTime Starting_Date {
            get {
                return this.starting_DateField;
            }
            set {
                this.starting_DateField = value;
                this.RaisePropertyChanged("Starting_Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Starting_DateSpecified {
            get {
                return this.starting_DateFieldSpecified;
            }
            set {
                this.starting_DateFieldSpecified = value;
                this.RaisePropertyChanged("Starting_DateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Starting_No {
            get {
                return this.starting_NoField;
            }
            set {
                this.starting_NoField = value;
                this.RaisePropertyChanged("Starting_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Ending_No {
            get {
                return this.ending_NoField;
            }
            set {
                this.ending_NoField = value;
                this.RaisePropertyChanged("Ending_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=5)]
        public System.DateTime Last_Date_Used {
            get {
                return this.last_Date_UsedField;
            }
            set {
                this.last_Date_UsedField = value;
                this.RaisePropertyChanged("Last_Date_Used");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Last_Date_UsedSpecified {
            get {
                return this.last_Date_UsedFieldSpecified;
            }
            set {
                this.last_Date_UsedFieldSpecified = value;
                this.RaisePropertyChanged("Last_Date_UsedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Last_No_Used {
            get {
                return this.last_No_UsedField;
            }
            set {
                this.last_No_UsedField = value;
                this.RaisePropertyChanged("Last_No_Used");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Warning_No {
            get {
                return this.warning_NoField;
            }
            set {
                this.warning_NoField = value;
                this.RaisePropertyChanged("Warning_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int Increment_by_No {
            get {
                return this.increment_by_NoField;
            }
            set {
                this.increment_by_NoField = value;
                this.RaisePropertyChanged("Increment_by_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Increment_by_NoSpecified {
            get {
                return this.increment_by_NoFieldSpecified;
            }
            set {
                this.increment_by_NoFieldSpecified = value;
                this.RaisePropertyChanged("Increment_by_NoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool Open {
            get {
                return this.openField;
            }
            set {
                this.openField = value;
                this.RaisePropertyChanged("Open");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OpenSpecified {
            get {
                return this.openFieldSpecified;
            }
            set {
                this.openFieldSpecified = value;
                this.RaisePropertyChanged("OpenSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/noserieslines")]
    public partial class NoSeriesLines_Filter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private NoSeriesLines_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public NoSeriesLines_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
                this.RaisePropertyChanged("Criteria");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/noserieslines")]
    public enum NoSeriesLines_Fields {
        
        /// <remarks/>
        Series_Code,
        
        /// <remarks/>
        Starting_Date,
        
        /// <remarks/>
        Starting_No,
        
        /// <remarks/>
        Ending_No,
        
        /// <remarks/>
        Last_Date_Used,
        
        /// <remarks/>
        Last_No_Used,
        
        /// <remarks/>
        Warning_No,
        
        /// <remarks/>
        Increment_by_No,
        
        /// <remarks/>
        Open,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/noserieslines", IsWrapped=true)]
    public partial class Read {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/noserieslines", Order=0)]
        public string Series_Code;
        
        public Read() {
        }
        
        public Read(string Series_Code) {
            this.Series_Code = Series_Code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/noserieslines", IsWrapped=true)]
    public partial class Read_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/noserieslines", Order=0)]
        public DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines NoSeriesLines;
        
        public Read_Result() {
        }
        
        public Read_Result(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines NoSeriesLines) {
            this.NoSeriesLines = NoSeriesLines;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/noserieslines", IsWrapped=true)]
    public partial class ReadByRecId {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/noserieslines", Order=0)]
        public string recId;
        
        public ReadByRecId() {
        }
        
        public ReadByRecId(string recId) {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/noserieslines", IsWrapped=true)]
    public partial class ReadByRecId_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/noserieslines", Order=0)]
        public DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines NoSeriesLines;
        
        public ReadByRecId_Result() {
        }
        
        public ReadByRecId_Result(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines NoSeriesLines) {
            this.NoSeriesLines = NoSeriesLines;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/noserieslines", IsWrapped=true)]
    public partial class ReadMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/noserieslines", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/noserieslines", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/noserieslines", Order=2)]
        public int setSize;
        
        public ReadMultiple() {
        }
        
        public ReadMultiple(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines_Filter[] filter, string bookmarkKey, int setSize) {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/noserieslines", IsWrapped=true)]
    public partial class ReadMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/noserieslines", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines[] ReadMultiple_Result1;
        
        public ReadMultiple_Result() {
        }
        
        public ReadMultiple_Result(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines[] ReadMultiple_Result1) {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/noserieslines", IsWrapped=true)]
    public partial class IsUpdated {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/noserieslines", Order=0)]
        public string Key;
        
        public IsUpdated() {
        }
        
        public IsUpdated(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/noserieslines", IsWrapped=true)]
    public partial class IsUpdated_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/noserieslines", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result() {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1) {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/noserieslines", IsWrapped=true)]
    public partial class GetRecIdFromKey {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/noserieslines", Order=0)]
        public string Key;
        
        public GetRecIdFromKey() {
        }
        
        public GetRecIdFromKey(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/noserieslines", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/noserieslines", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result() {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1) {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create", WrapperNamespace="urn:microsoft-dynamics-schemas/page/noserieslines", IsWrapped=true)]
    public partial class Create {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/noserieslines", Order=0)]
        public DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines NoSeriesLines;
        
        public Create() {
        }
        
        public Create(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines NoSeriesLines) {
            this.NoSeriesLines = NoSeriesLines;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/noserieslines", IsWrapped=true)]
    public partial class Create_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/noserieslines", Order=0)]
        public DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines NoSeriesLines;
        
        public Create_Result() {
        }
        
        public Create_Result(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines NoSeriesLines) {
            this.NoSeriesLines = NoSeriesLines;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/noserieslines", IsWrapped=true)]
    public partial class CreateMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/noserieslines", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines[] NoSeriesLines_List;
        
        public CreateMultiple() {
        }
        
        public CreateMultiple(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines[] NoSeriesLines_List) {
            this.NoSeriesLines_List = NoSeriesLines_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/noserieslines", IsWrapped=true)]
    public partial class CreateMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/noserieslines", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines[] NoSeriesLines_List;
        
        public CreateMultiple_Result() {
        }
        
        public CreateMultiple_Result(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines[] NoSeriesLines_List) {
            this.NoSeriesLines_List = NoSeriesLines_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="urn:microsoft-dynamics-schemas/page/noserieslines", IsWrapped=true)]
    public partial class Update {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/noserieslines", Order=0)]
        public DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines NoSeriesLines;
        
        public Update() {
        }
        
        public Update(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines NoSeriesLines) {
            this.NoSeriesLines = NoSeriesLines;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/noserieslines", IsWrapped=true)]
    public partial class Update_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/noserieslines", Order=0)]
        public DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines NoSeriesLines;
        
        public Update_Result() {
        }
        
        public Update_Result(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines NoSeriesLines) {
            this.NoSeriesLines = NoSeriesLines;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/noserieslines", IsWrapped=true)]
    public partial class UpdateMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/noserieslines", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines[] NoSeriesLines_List;
        
        public UpdateMultiple() {
        }
        
        public UpdateMultiple(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines[] NoSeriesLines_List) {
            this.NoSeriesLines_List = NoSeriesLines_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/noserieslines", IsWrapped=true)]
    public partial class UpdateMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/noserieslines", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines[] NoSeriesLines_List;
        
        public UpdateMultiple_Result() {
        }
        
        public UpdateMultiple_Result(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines[] NoSeriesLines_List) {
            this.NoSeriesLines_List = NoSeriesLines_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete", WrapperNamespace="urn:microsoft-dynamics-schemas/page/noserieslines", IsWrapped=true)]
    public partial class Delete {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/noserieslines", Order=0)]
        public string Key;
        
        public Delete() {
        }
        
        public Delete(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/noserieslines", IsWrapped=true)]
    public partial class Delete_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_Result", Namespace="urn:microsoft-dynamics-schemas/page/noserieslines", Order=0)]
        public bool Delete_Result1;
        
        public Delete_Result() {
        }
        
        public Delete_Result(bool Delete_Result1) {
            this.Delete_Result1 = Delete_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NoSeriesLines_PortChannel : DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NoSeriesLines_PortClient : System.ServiceModel.ClientBase<DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines_Port>, DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines_Port {
        
        public NoSeriesLines_PortClient() {
        }
        
        public NoSeriesLines_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NoSeriesLines_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NoSeriesLines_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NoSeriesLines_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.Read_Result DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines_Port.Read(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.Read request) {
            return base.Channel.Read(request);
        }
        
        public DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines Read(string Series_Code) {
            DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.Read inValue = new DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.Read();
            inValue.Series_Code = Series_Code;
            DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.Read_Result retVal = ((DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines_Port)(this)).Read(inValue);
            return retVal.NoSeriesLines;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.Read_Result> DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines_Port.ReadAsync(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.Read request) {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.Read_Result> ReadAsync(string Series_Code) {
            DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.Read inValue = new DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.Read();
            inValue.Series_Code = Series_Code;
            return ((DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.ReadByRecId_Result DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines_Port.ReadByRecId(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.ReadByRecId request) {
            return base.Channel.ReadByRecId(request);
        }
        
        public DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines ReadByRecId(string recId) {
            DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.ReadByRecId inValue = new DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.ReadByRecId();
            inValue.recId = recId;
            DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.ReadByRecId_Result retVal = ((DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines_Port)(this)).ReadByRecId(inValue);
            return retVal.NoSeriesLines;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.ReadByRecId_Result> DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines_Port.ReadByRecIdAsync(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.ReadByRecId request) {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.ReadByRecId_Result> ReadByRecIdAsync(string recId) {
            DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.ReadByRecId inValue = new DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.ReadByRecId();
            inValue.recId = recId;
            return ((DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.ReadMultiple_Result DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines_Port.ReadMultiple(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.ReadMultiple request) {
            return base.Channel.ReadMultiple(request);
        }
        
        public DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines[] ReadMultiple(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines_Filter[] filter, string bookmarkKey, int setSize) {
            DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.ReadMultiple inValue = new DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.ReadMultiple_Result retVal = ((DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines_Port)(this)).ReadMultiple(inValue);
            return retVal.ReadMultiple_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.ReadMultiple_Result> DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines_Port.ReadMultipleAsync(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.ReadMultiple request) {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.ReadMultiple_Result> ReadMultipleAsync(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines_Filter[] filter, string bookmarkKey, int setSize) {
            DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.ReadMultiple inValue = new DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.IsUpdated_Result DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines_Port.IsUpdated(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.IsUpdated request) {
            return base.Channel.IsUpdated(request);
        }
        
        public bool IsUpdated(string Key) {
            DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.IsUpdated inValue = new DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.IsUpdated();
            inValue.Key = Key;
            DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.IsUpdated_Result retVal = ((DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines_Port)(this)).IsUpdated(inValue);
            return retVal.IsUpdated_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.IsUpdated_Result> DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines_Port.IsUpdatedAsync(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.IsUpdated request) {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.IsUpdated_Result> IsUpdatedAsync(string Key) {
            DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.IsUpdated inValue = new DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.IsUpdated();
            inValue.Key = Key;
            return ((DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.GetRecIdFromKey_Result DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines_Port.GetRecIdFromKey(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKey(request);
        }
        
        public string GetRecIdFromKey(string Key) {
            DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.GetRecIdFromKey inValue = new DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.GetRecIdFromKey();
            inValue.Key = Key;
            DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.GetRecIdFromKey_Result retVal = ((DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines_Port)(this)).GetRecIdFromKey(inValue);
            return retVal.GetRecIdFromKey_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.GetRecIdFromKey_Result> DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines_Port.GetRecIdFromKeyAsync(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key) {
            DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.GetRecIdFromKey inValue = new DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.GetRecIdFromKey();
            inValue.Key = Key;
            return ((DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.Create_Result DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines_Port.Create(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.Create request) {
            return base.Channel.Create(request);
        }
        
        public void Create(ref DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines NoSeriesLines) {
            DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.Create inValue = new DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.Create();
            inValue.NoSeriesLines = NoSeriesLines;
            DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.Create_Result retVal = ((DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines_Port)(this)).Create(inValue);
            NoSeriesLines = retVal.NoSeriesLines;
        }
        
        public System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.Create_Result> CreateAsync(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.Create request) {
            return base.Channel.CreateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.CreateMultiple_Result DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines_Port.CreateMultiple(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.CreateMultiple request) {
            return base.Channel.CreateMultiple(request);
        }
        
        public void CreateMultiple(ref DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines[] NoSeriesLines_List) {
            DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.CreateMultiple inValue = new DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.CreateMultiple();
            inValue.NoSeriesLines_List = NoSeriesLines_List;
            DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.CreateMultiple_Result retVal = ((DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines_Port)(this)).CreateMultiple(inValue);
            NoSeriesLines_List = retVal.NoSeriesLines_List;
        }
        
        public System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.CreateMultiple_Result> CreateMultipleAsync(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.CreateMultiple request) {
            return base.Channel.CreateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.Update_Result DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines_Port.Update(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.Update request) {
            return base.Channel.Update(request);
        }
        
        public void Update(ref DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines NoSeriesLines) {
            DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.Update inValue = new DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.Update();
            inValue.NoSeriesLines = NoSeriesLines;
            DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.Update_Result retVal = ((DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines_Port)(this)).Update(inValue);
            NoSeriesLines = retVal.NoSeriesLines;
        }
        
        public System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.Update_Result> UpdateAsync(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.Update request) {
            return base.Channel.UpdateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.UpdateMultiple_Result DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines_Port.UpdateMultiple(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.UpdateMultiple request) {
            return base.Channel.UpdateMultiple(request);
        }
        
        public void UpdateMultiple(ref DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines[] NoSeriesLines_List) {
            DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.UpdateMultiple inValue = new DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.UpdateMultiple();
            inValue.NoSeriesLines_List = NoSeriesLines_List;
            DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.UpdateMultiple_Result retVal = ((DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines_Port)(this)).UpdateMultiple(inValue);
            NoSeriesLines_List = retVal.NoSeriesLines_List;
        }
        
        public System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.UpdateMultiple_Result> UpdateMultipleAsync(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.UpdateMultiple request) {
            return base.Channel.UpdateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.Delete_Result DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines_Port.Delete(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.Delete request) {
            return base.Channel.Delete(request);
        }
        
        public bool Delete(string Key) {
            DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.Delete inValue = new DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.Delete();
            inValue.Key = Key;
            DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.Delete_Result retVal = ((DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines_Port)(this)).Delete(inValue);
            return retVal.Delete_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.Delete_Result> DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines_Port.DeleteAsync(DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.Delete request) {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.Delete_Result> DeleteAsync(string Key) {
            DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.Delete inValue = new DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.Delete();
            inValue.Key = Key;
            return ((DynamicsNav.WebserviceTests.SOAP.NoSeriesLines.NoSeriesLines_Port)(this)).DeleteAsync(inValue);
        }
    }
}
